import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveShapes,interpolateShapes,initialFrames} from '../lib/animation.js';
test('earlier color changes carry through independent edits until a later explicit color',()=>{const fs=structuredClone(initialFrames);fs[0].changes.circle.color='#ff0000';assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').color,'#ff0000');assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').x,400);assert.equal(resolveShapes(fs,2).find(s=>s.id==='circle').color,'#e7aa8d')});
test('blank added frames inherit resolved properties without freezing them',()=>{const fs=structuredClone(initialFrames);fs.splice(1,0,{id:'new',changes:{}});fs[0].changes.circle.w=180;assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').w,180);assert.equal(resolveShapes(fs,2).find(s=>s.id==='circle').w,200)});
test('midpoint interpolates geometry and color',()=>{const fs=structuredClone(initialFrames);fs[0].changes.circle.color='#000000';fs[1].changes.circle.color='#ffffff';const s=interpolateShapes(fs,.5).find(s=>s.id==='circle');assert.equal(s.x,310);assert.equal(s.w,180);assert.equal(s.color,'#808080')});
test('deletion carries forward and fades out',()=>{const fs=structuredClone(initialFrames);fs[1].changes.circle={visible:false};assert.equal(resolveShapes(fs,2).some(s=>s.id==='circle'),false);assert.equal(interpolateShapes(fs,.5).find(s=>s.id==='circle').opacity,.5)});
test('new shapes do not appear on earlier frames and fade in',()=>{const fs=structuredClone(initialFrames);fs[1].changes.new={...fs[0].changes.circle,x:100};assert.equal(resolveShapes(fs,0).some(s=>s.id==='new'),false);assert.equal(interpolateShapes(fs,.5).find(s=>s.id==='new').opacity,.5)});

import {findSnap,anchorPoint,linePoint,lineGeometry,fromLinePoints,resolveConnections} from '../lib/animation.js';
const close=(actual,expected)=>{assert.ok(Math.abs(actual.x-expected.x)<1e-4,`x: ${actual.x} != ${expected.x}`);assert.ok(Math.abs(actual.y-expected.y)<1e-4,`y: ${actual.y} != ${expected.y}`)};
function connectedScene(){const circle={...initialFrames[0].changes.circle,id:'circle',x:0,y:0,w:100,h:100};const line={...initialFrames[0].changes.line,id:'line',x:100,y:50,w:150,h:0,cx:75,cy:0,startLink:{id:'circle',kind:'circle',angle:0}};return [{id:'a',changes:{circle,line}},{id:'b',changes:{circle:{x:160,y:80,w:200,h:140,rotation:45}}}]}
test('circle connections follow translation, resizing, and rotation across frames',()=>{const fs=connectedScene();for(const i of [0,1]){const shapes=resolveShapes(fs,i),c=shapes.find(s=>s.id==='circle'),l=shapes.find(s=>s.id==='line');close(linePoint(l,0),anchorPoint(c,l.startLink))}});
test('circle connections stay exact throughout smooth playback',()=>{const fs=connectedScene();for(const t of [.1,.25,.5,.75,.9]){const shapes=interpolateShapes(fs,t),c=shapes.find(s=>s.id==='circle'),l=shapes.find(s=>s.id==='line');close(linePoint(l,0),anchorPoint(c,l.startLink))}});
test('line-to-line connections follow the target curve and chained connections',()=>{const fs=connectedScene();fs[0].changes.branch={...fs[0].changes.line,id:'branch',x:175,y:50,w:0,h:200,cx:0,cy:100,startLink:{id:'line',kind:'line',t:.5}};fs[1].changes.line={cy:200};for(const position of [0,.4,1]){const shapes=interpolateShapes(fs,position),branch=shapes.find(s=>s.id==='branch'),line=shapes.find(s=>s.id==='line');close(linePoint(branch,0),linePoint(line,.5))}});
test('both endpoints can stay connected to different moving circles',()=>{const fs=connectedScene();fs[0].changes.other={...fs[0].changes.circle,id:'other',x:300};fs[0].changes.line.endLink={id:'other',kind:'circle',angle:Math.PI};fs[1].changes.other={y:-100,w:160};const shapes=interpolateShapes(fs,.5),l=shapes.find(s=>s.id==='line');for(const [key,t]of [['startLink',0],['endLink',1]])close(linePoint(l,t),anchorPoint(shapes.find(s=>s.id===l[key].id),l[key]))});
test('snap finds the circle perimeter and line endpoints',()=>{const shapes=resolveShapes(connectedScene(),0);const c=findSnap(shapes,{x:0,y:52},'new',12);assert.equal(c.link.id,'circle');assert.equal(c.link.kind,'circle');const l=findSnap(shapes,{x:252,y:51},'new',12);assert.equal(l.link.id,'line');assert.equal(l.link.t,1);assert.equal(findSnap(shapes,{x:900,y:900},'new',12),null)});
test('snapping prevents self links and dependency cycles',()=>{const shapes=resolveShapes(connectedScene(),0);const branch={...shapes.find(s=>s.id==='line'),id:'branch',startLink:{id:'line',kind:'line',t:1}};const result=findSnap([...shapes,branch],{x:250,y:50},'line',10);assert.equal(result,null)});
test('explicit disconnection inherits and leaves resolved geometry in place',()=>{const fs=connectedScene(),shapes=resolveShapes(fs,1),line=shapes.find(s=>s.id==='line'),g=lineGeometry(line);fs[1].changes.line={...fromLinePoints(g.start,g.end,g.control),startLink:null,endLink:null};fs.push({id:'c',changes:{circle:{x:900}}});close(linePoint(resolveShapes(fs,2).find(s=>s.id==='line'),0),g.start)});
test('a changed attachment interpolates toward the new anchor without a jump',()=>{const fs=connectedScene();fs[1].changes.line={startLink:{id:'circle',kind:'circle',angle:Math.PI}};const expected=linePoint(resolveShapes(fs,1).find(s=>s.id==='line'),0),near=linePoint(interpolateShapes(fs,.999999).find(s=>s.id==='line'),0);assert.ok(Math.hypot(expected.x-near.x,expected.y-near.y)<.001)});
test('connections survive serialization and earlier target edits',()=>{const fs=JSON.parse(JSON.stringify(connectedScene()));fs[0].changes.circle.h=180;const shapes=resolveShapes(fs,0),line=shapes.find(s=>s.id==='line');close(linePoint(line,0),{x:100,y:90});assert.equal(resolveConnections(shapes).length,2)});
