import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveShapes,interpolateShapes,initialFrames} from '../lib/animation.js';
test('earlier color changes carry through independent edits until a later explicit color',()=>{const fs=structuredClone(initialFrames);fs[0].changes.circle.color='#ff0000';assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').color,'#ff0000');assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').x,400);assert.equal(resolveShapes(fs,2).find(s=>s.id==='circle').color,'#e7aa8d')});
test('blank added frames inherit resolved properties without freezing them',()=>{const fs=structuredClone(initialFrames);fs.splice(1,0,{id:'new',changes:{}});fs[0].changes.circle.w=180;assert.equal(resolveShapes(fs,1).find(s=>s.id==='circle').w,180);assert.equal(resolveShapes(fs,2).find(s=>s.id==='circle').w,200)});
test('midpoint interpolates geometry and color',()=>{const fs=structuredClone(initialFrames);fs[0].changes.circle.color='#000000';fs[1].changes.circle.color='#ffffff';const s=interpolateShapes(fs,.5).find(s=>s.id==='circle');assert.equal(s.x,310);assert.equal(s.w,180);assert.equal(s.color,'#808080')});
test('deletion carries forward and fades out',()=>{const fs=structuredClone(initialFrames);fs[1].changes.circle={visible:false};assert.equal(resolveShapes(fs,2).some(s=>s.id==='circle'),false);assert.equal(interpolateShapes(fs,.5).find(s=>s.id==='circle').opacity,.5)});
test('new shapes do not appear on earlier frames and fade in',()=>{const fs=structuredClone(initialFrames);fs[1].changes.new={...fs[0].changes.circle,x:100};assert.equal(resolveShapes(fs,0).some(s=>s.id==='new'),false);assert.equal(interpolateShapes(fs,.5).find(s=>s.id==='new').opacity,.5)});

import {findSnap,anchorPoint,linePoint,lineGeometry,fromLinePoints,resolveConnections} from '../lib/animation.js';
const close=(actual,expected)=>{assert.ok(Math.abs(actual.x-expected.x)<1e-4,`x: ${actual.x} != ${expected.x}`);assert.ok(Math.abs(actual.y-expected.y)<1e-4,`y: ${actual.y} != ${expected.y}`)};
function connectedScene(){const circle={...initialFrames[0].changes.circle,id:'circle',x:0,y:0,w:100,h:100};const line={...initialFrames[0].changes.line,id:'line',x:100,y:50,w:150,h:0,cx:75,cy:0,startLink:{id:'circle',kind:'circle',angle:0}};return [{id:'a',changes:{circle,line}},{id:'b',changes:{circle:{x:160,y:80,w:200,h:140,rotation:45}}}]}
test('circle connections follow translation, resizing, and rotation across frames',()=>{const fs=connectedScene();for(const i of [0,1]){const shapes=resolveShapes(fs,i),c=shapes.find(s=>s.id==='circle'),l=shapes.find(s=>s.id==='line');close(linePoint(l,0),anchorPoint(c,l.startLink))}});
test('circle connections stay exact throughout smooth playback',()=>{const fs=connectedScene();for(const t of [.1,.25,.5,.75,.9]){const shapes=interpolateShapes(fs,t),c=shapes.find(s=>s.id==='circle'),l=shapes.find(s=>s.id==='line');close(linePoint(l,0),anchorPoint(c,l.startLink))}});
test('line-to-line connections follow the target curve and chained connections',()=>{const fs=connectedScene();fs[0].changes.branch={...fs[0].changes.line,id:'branch',x:175,y:50,w:0,h:200,cx:0,cy:100,startLink:{id:'line',kind:'line',t:.5}};fs[1].changes.line={cy:200};for(const position of [0,.4,1]){const shapes=interpolateShapes(fs,position),branch=shapes.find(s=>s.id==='branch'),line=shapes.find(s=>s.id==='line');close(linePoint(branch,0),linePoint(line,.5))}});
test('both endpoints can stay connected to different moving circles',()=>{const fs=connectedScene();fs[0].changes.other={...fs[0].changes.circle,id:'other',x:300};fs[0].changes.line.endLink={id:'other',kind:'circle',angle:Math.PI};fs[1].changes.other={y:-100,w:160};const shapes=interpolateShapes(fs,.5),l=shapes.find(s=>s.id==='line');for(const [key,t]of [['startLink',0],['endLink',1]])close(linePoint(l,t),anchorPoint(shapes.find(s=>s.id===l[key].id),l[key]))});
test('snap finds the circle perimeter and line endpoints',()=>{const shapes=resolveShapes(connectedScene(),0);const c=findSnap(shapes,{x:0,y:52},'new',12);assert.equal(c.link.id,'circle');assert.equal(c.link.kind,'circle');const l=findSnap(shapes,{x:252,y:51},'new',12);assert.equal(l.link.id,'line');assert.equal(l.link.t,1);assert.equal(findSnap(shapes,{x:900,y:900},'new',12),null)});
test('snapping prevents self links and dependency cycles',()=>{const shapes=resolveShapes(connectedScene(),0);const branch={...shapes.find(s=>s.id==='line'),id:'branch',startLink:{id:'line',kind:'line',t:1}};const result=findSnap([...shapes,branch],{x:250,y:50},'line',10);assert.equal(result,null)});
test('explicit disconnection inherits and leaves resolved geometry in place',()=>{const fs=connectedScene(),shapes=resolveShapes(fs,1),line=shapes.find(s=>s.id==='line'),g=lineGeometry(line);fs[1].changes.line={...fromLinePoints(g.start,g.end,g.control),startLink:null,endLink:null};fs.push({id:'c',changes:{circle:{x:900}}});close(linePoint(resolveShapes(fs,2).find(s=>s.id==='line'),0),g.start)});
test('a changed attachment interpolates toward the new anchor without a jump',()=>{const fs=connectedScene();fs[1].changes.line={startLink:{id:'circle',kind:'circle',angle:Math.PI}};const expected=linePoint(resolveShapes(fs,1).find(s=>s.id==='line'),0),near=linePoint(interpolateShapes(fs,.999999).find(s=>s.id==='line'),0);assert.ok(Math.hypot(expected.x-near.x,expected.y-near.y)<.001)});
test('connections survive serialization and earlier target edits',()=>{const fs=JSON.parse(JSON.stringify(connectedScene()));fs[0].changes.circle.h=180;const shapes=resolveShapes(fs,0),line=shapes.find(s=>s.id==='line');close(linePoint(line,0),{x:100,y:90});assert.equal(resolveConnections(shapes).length,2)});

import {alignCamera,snapEndpoint,movieDuration} from '../lib/view.js';
import {supportedMovieType,movieDimensions,recordMovie} from '../lib/movie.js';
test('looped playback transitions from final state back to the resolved first frame',()=>{const fs=structuredClone(initialFrames);const a=resolveShapes(fs,2).find(s=>s.id==='circle'),b=resolveShapes(fs,0).find(s=>s.id==='circle'),middle=interpolateShapes(fs,2.5,'linear',true).find(s=>s.id==='circle');assert.equal(middle.x,(a.x+b.x)/2);assert.equal(middle.w,(a.w+b.w)/2);assert.equal(interpolateShapes(fs,3,'smooth',true).find(s=>s.id==='circle').x,b.x);assert.equal(interpolateShapes(fs,2.5,'linear',false).find(s=>s.id==='circle').x,a.x)});
test('connections follow targets on the closing transition too',()=>{const fs=connectedScene();const shapes=interpolateShapes(fs,1.5,'smooth',true),line=shapes.find(s=>s.id==='line'),circle=shapes.find(s=>s.id==='circle');close(linePoint(line,0),anchorPoint(circle,line.startLink))});
test('loop adds exactly one transition to export duration',()=>{assert.equal(movieDuration(3,1,true),3);assert.equal(movieDuration(3,1,false),2);assert.equal(movieDuration(3,.5,true),1.5);assert.equal(movieDuration(1,1,true),1)});
test('camera settles with grid on the top, left and right edges',()=>{for(const [w,h,baseScale,zoom]of [[390,650,.4375,1.31],[1280,720,1.2,.73],[844,220,.3214,2.8]]){const v=alignCamera({w,h},baseScale,zoom,{x:33.4,y:-53.1}),scale=baseScale*v.zoom,step=80*scale,x=w/2-460*scale+v.pan.x,y=h/2-300*scale+v.pan.y;for(const n of [x/step,y/step,(w-x)/step])assert.ok(Math.abs(n-Math.round(n))<1e-8);assert.ok(v.zoom>=.4&&v.zoom<=4)}});
test('grid attraction wins over a nearby off-grid line when distances are similar',()=>{const line={...initialFrames[0].changes.line,id:'target',x:17,y:-80,w:0,h:160,cx:0,cy:80};const result=snapEndpoint([line],{x:7,y:8},'new',1,true);assert.equal(result.kind,'grid');close(result.point,{x:0,y:0});assert.equal(result.link,null)});
test('deliberate line attachment still works away from a grid intersection',()=>{const line={...initialFrames[0].changes.line,id:'target',x:40,y:0,w:0,h:160,cx:0,cy:80};const result=snapEndpoint([line],{x:42,y:35},'new',1,true);assert.equal(result.link.id,'target');assert.equal(result.kind,'shape');const free=snapEndpoint([line],{x:42,y:35},'new',1,false);close(free.point,{x:42,y:35});assert.equal(free.link,null)});
test('a line on the grid can stay attached and aligned',()=>{const line={...initialFrames[0].changes.line,id:'target',x:0,y:0,w:160,h:0,cx:80,cy:0};const result=snapEndpoint([line],{x:1,y:2},'new',1,true);assert.equal(result.kind,'shape');close(result.point,{x:0,y:0})});
test('movie format prefers MP4 but negotiates WebM for other encoders',()=>{assert.equal(supportedMovieType({isTypeSupported:type=>type==='video/mp4'}),'video/mp4');assert.equal(supportedMovieType({isTypeSupported:type=>type==='video/webm;codecs=vp8'}),'video/webm;codecs=vp8');assert.equal(supportedMovieType({isTypeSupported:()=>false}),null);assert.equal(supportedMovieType(null),null)});
test('movie dimensions preserve the viewport aspect ratio with even encoder sizes',()=>{const p=movieDimensions(390,650);assert.equal(p.width%2,0);assert.equal(p.height%2,0);assert.equal(p.height,1080);assert.ok(Math.abs(p.width/p.height-390/650)<.002)});

// Exercise exporter timing, Blob delivery and resource cleanup without a browser UI.
async function withMovieRuntime(run){
 const names=['MediaRecorder','document','requestAnimationFrame','cancelAnimationFrame','setTimeout','clearTimeout'];const original=Object.fromEntries(names.map(k=>[k,globalThis[k]]));let clock=performance.now(),nextId=0;const pending=new Map(),listeners=new Map(),stats={stopped:0,lastProgress:0,movieStopped:0};
 function schedule(fn,delay){const id=++nextId;pending.set(id,{fn,time:clock+delay});return id}
 globalThis.requestAnimationFrame=fn=>schedule(()=>fn(clock),34);globalThis.cancelAnimationFrame=id=>pending.delete(id);globalThis.setTimeout=(fn,delay)=>schedule(fn,delay);globalThis.clearTimeout=id=>pending.delete(id);
 globalThis.document={hidden:false,addEventListener:(k,fn)=>listeners.set(k,fn),removeEventListener:k=>listeners.delete(k)};
 globalThis.MediaRecorder=class{static isTypeSupported(t){return t==='video/mp4'}constructor(stream,options){this.mimeType=options.mimeType;this.state='inactive'}start(){this.state='recording';schedule(()=>this.onstart(),0)}stop(){this.state='inactive';stats.movieStopped++;schedule(()=>{this.ondataavailable({data:new Blob(['encoded video'])});this.onstop()},0)}};
 const ctx=new Proxy({},{get:()=>()=>{},set:()=>true});const canvas={width:648,height:1080,getContext:()=>ctx,captureStream:()=>({getTracks:()=>[{stop:()=>stats.stopped++}]})};
 const options={canvas,frames:initialFrames,duration:.1,loop:true,easing:'smooth',view:{width:390,height:650,scale:.4,origin:{x:0,y:0}},onProgress:p=>stats.lastProgress=p};
 const pump=async()=>{for(let i=0;pending.size&&i<1000;i++){const[id,item]=[...pending].sort((a,b)=>a[1].time-b[1].time)[0];pending.delete(id);clock=item.time;item.fn();await Promise.resolve()}};
 try{await run({options,pump,stats,listeners})}finally{for(const name of names){if(original[name]===undefined)delete globalThis[name];else globalThis[name]=original[name]}}
}
test('movie export produces a correctly named Blob and stops capture tracks',async()=>withMovieRuntime(async({options,pump,stats})=>{const promise=recordMovie(options);await pump();const result=await promise;assert.equal(result.extension,'mp4');assert.equal(result.blob.type,'video/mp4');assert.ok(result.blob.size>0);assert.equal(stats.lastProgress,1);assert.equal(stats.stopped,1);assert.equal(stats.movieStopped,1)}));
test('cancelled exports reject and release capture resources',async()=>withMovieRuntime(async({options,pump,stats})=>{const controller=new AbortController(),promise=recordMovie({...options,signal:controller.signal});const rejected=assert.rejects(promise,{name:'AbortError'});controller.abort();await pump();await rejected;assert.equal(stats.stopped,1)}));
test('hiding the editor aborts rather than delivering an incomplete movie',async()=>withMovieRuntime(async({options,pump,stats,listeners})=>{const promise=recordMovie(options);const rejected=assert.rejects(promise,/editor was hidden/);document.hidden=true;listeners.get('visibilitychange')();await pump();await rejected;assert.equal(stats.stopped,1)}));
