'use client';
import {useState,useEffect,useRef,useCallback,useMemo} from 'react';
import {MousePointer2,ImagePlus,Import,Brush,Minus,Circle,Square,Magnet,Undo2,Redo2,Settings2,Play,Pause,Trash2,Copy,X,Film,ClipboardPaste,Focus,Group,LogOut,Spline,ArrowUp,ArrowDown,FileDown,FolderOpen,FilePlus2,Lock,Unlock,Link2,SlidersHorizontal} from 'lucide-react';
import {resolveShapes,interpolateShapes,interpolateScene,drawShape,initialFrames,worldToLocal,localToWorld,lineGeometry,fromLinePoints,symbolCycleDuration,linePoint,lineHandles,linePatch,patchLineHandles} from '../lib/animation';
import {snapEndpoint,alignCamera,drawGrid,startingGridScale,gridLevel,gridSpacing,MAX_ZOOM,centerCamera} from '../lib/view';
import MovieExport from './movie-export';
import TouchPreview from './touch-preview';
import Voiceover from './voiceover';
import MovieSave from './movie-save';
import CameraOverlay,{useFrontCamera} from './camera-overlay';
import FrameTimeline from './frame-timeline';
import {boxSelectParts,mergePoints,moveParts,partsBounds,reorderFrames,deleteFrame,styleSelection,selectionBounds,reorderSelection,isGroupSelection,symbolLocalBounds,shapeBounds} from '../lib/editing';
import {DEFAULT_STYLE,DEFAULT_EASING,newShapeStyle,STROKE_STYLES} from '../lib/defaults';
import {frameStart,frameSeconds,timelinePosition} from '../lib/timing';
import {symbolIsShared,unlinkSymbolInstance,timelineOf,updateTimeline,groupIntoSymbol,copyShapes,pasteShapes,copyLinkedShapes,breakSymbol} from '../lib/symbols';
import useImages from './use-images';
import {importImageFile,preloadImages} from '../lib/images';
import {importedImage,importedAnimation} from '../lib/importing';
import useProjectStorage from './use-project-storage';
import EditorDialog from './editor-dialog';
import StrokeWidthInput from './stroke-width-input';
import {brushGeometry} from '../lib/brush';
import {selectionControls,selectionScale,rotationMatrix,transformParts} from '../lib/selection-transform';
import {rotationControl,rotationAngle,rotateShape} from '../lib/rotation';
import {transformPoint,inverse} from '../lib/matrix';
import {downloadAnimation,parseAnimation} from '../lib/project-storage';
import {MOVIE_FPS} from '../lib/movie';
const uid=()=>Math.random().toString(36).slice(2,10);
const toolList=[['select',MousePointer2,'Select','V'],['brush',Brush,'Brush','D'],['line',Minus,'Straight line','L'],['bezier',Spline,'Bézier line','B'],['circle',Circle,'Circle','O'],['rect',Square,'Square','R']];
function IconButton({icon:Icon,label,active,className='',...props}){return <button type="button" className={`icon-button ${active?'active':''} ${className}`} title={label} aria-label={label} aria-pressed={active===undefined?undefined:active} {...props}><Icon size={20} strokeWidth={1.65}/></button>}
export default function Editor(){
 const imageVersion=useImages();
 const[importOpen,setImportOpen]=useState(false),[importBusy,setImportBusy]=useState(false);
 const[project,setProject]=useState(()=>({frames:structuredClone(initialFrames),symbols:{},duration:1,easing:DEFAULT_EASING})),[scope,setScope]=useState(null),[path,setPath]=useState([]);
 const timeline=timelineOf(project,scope),{frames,duration,easing}=timeline;
 const setFrames=next=>setProject(p=>updateTimeline(p,scope,{frames:typeof next==='function'?next(timelineOf(p,scope).frames):next}));
 const setDuration=value=>{remember();setProject(p=>updateTimeline(p,scope,{duration:value}))},setEasing=value=>{remember();setProject(p=>updateTimeline(p,scope,{easing:value}))};
 const[frame,setFrame]=useState(0),[selected,setSelected]=useState([]),[selectedPoints,setSelectedPoints]=useState({}),[tool,setTool]=useState('select'),[clipboard,setClipboard]=useState(null),[canvasMenu,setCanvasMenu]=useState(null);
 const[snap,setSnap]=useState(true),[grid,setGrid]=useState(true),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[sceneTime,setSceneTime]=useState(0),[settings,setSettings]=useState(false),[snapHint,setSnapHint]=useState(null),[touchPreview,setTouchPreview]=useState(null),[exportOpen,setExportOpen]=useState(false),[movieFps,setMovieFps]=useState(30),[voiceMode,setVoiceMode]=useState(false),[voicePaused,setVoicePaused]=useState(false),[recordedMovie,setRecordedMovie]=useState(null);
 const[drawingStyle,setDrawingStyle]=useState(DEFAULT_STYLE),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[size,setSize]=useState({w:1000,h:650});
 const[copyNotice,setCopyNotice]=useState(null);
 useEffect(()=>{if(!copyNotice)return;const timer=setTimeout(()=>setCopyNotice(null),1600);return()=>clearTimeout(timer)},[copyNotice]);
 function notifyCopy(text){setCopyNotice({text,id:uid()})}
 const[marquee,setMarquee]=useState(null),[manipulating,setManipulating]=useState(false);
 const[downloadError,setDownloadError]=useState(''),[projectError,setProjectError]=useState(''),[styleOpen,setStyleOpen]=useState(false),[locksOpen,setLocksOpen]=useState(false),[newOpen,setNewOpen]=useState(false);
 const loop=true;
 const preferences=useMemo(()=>({snap,grid,loop:true,movieFps,drawingStyle}),[snap,grid,movieFps,drawingStyle]);
 const editorState=useMemo(()=>({scope,path,frame,zoom,pan}),[scope,path,frame,zoom,pan]);
 const savedState={project,preferences,editor:editorState};
 const storage=useProjectStorage(savedState,saved=>{
  setProject(saved.project);const p=saved.preferences,e=saved.editor;setSnap(p.snap);setGrid(p.grid);setMovieFps(p.movieFps);setDrawingStyle(p.drawingStyle);
  setScope(e.scope);setPath(e.path);setFrame(e.frame);setPosition(e.frame);setSceneTime(frameStart(timelineOf(saved.project,e.scope).frames,e.frame,timelineOf(saved.project,e.scope).duration));setZoom(e.zoom);setPan(e.pan);
 });
 function saveJson(){try{downloadAnimation(savedState);setDownloadError('')}catch{setDownloadError('The JSON file could not be downloaded. Please try again.')}}
 const camera=useFrontCamera(size);
 const canvasRef=useRef(null),stageRef=useRef(null),gesture=useRef(null),pointers=useRef(new Map()),framesRef=useRef(frames),projectRef=useRef(project),settingsRef=useRef(null),settingsButtonRef=useRef(null),viewRef=useRef(null),wheelTimer=useRef(null),voiceTween=useRef(null),voiceScene=useRef([]),voiceTime=useRef(0),renderScene=useRef(null),voiceModeRef=useRef(false),recordingView=useRef(null),lastTap=useRef(null),photoInput=useRef(null),importInput=useRef(null),importTarget=useRef(null),loadInput=useRef(null),loadRequest=useRef(0);
 framesRef.current=frames;projectRef.current=project;
 const shapes=resolveShapes(frames,frame),selectedShapes=shapes.filter(s=>!s.locked&&(selected.includes(s.id)||selectedPoints[s.id]?.length)),shape=selected.length===1&&!Object.keys(selectedPoints).length?selectedShapes[0]:null,bounds=partsBounds(shapes,selected,selectedPoints,{symbols:project.symbols,time:sceneTime}),styleShapes=selectedShapes.filter(s=>s.type!=='symbol'&&s.type!=='image'),symbolShapes=selectedShapes.filter(s=>s.type==='symbol'),lockedShapes=shapes.filter(s=>s.locked);
 const baseScale=startingGridScale(size.w),scale=baseScale*zoom,level=gridLevel(zoom),spacing=gridSpacing(zoom),origin={x:pan.x,y:pan.y},canPlay=frames.length>1||symbolCycleDuration(shapes,project.symbols)>0;
 recordingView.current={width:size.w,height:size.h,scale,origin,gridLevel:level};
 const getRecordingScene=useCallback(()=>({view:recordingView.current,shapes:voiceScene.current,includeGrid:viewRef.current.grid,symbols:projectRef.current.symbols,time:voiceTime.current}),[]);
 viewRef.current={size,baseScale,zoom,pan,scale,origin,snap,grid};voiceModeRef.current=voiceMode;
 const snapshot=()=>({project:projectRef.current,scope,path,frame,zoom,pan});
 const remember=()=>{setHistory(h=>[...h.slice(-49),snapshot()]);setFuture([])};
 useEffect(()=>{void preloadImages(project).catch(()=>setProjectError('An imported image could not be loaded.'))},[project]);
 function clearSelection(){setSelected([]);setSelectedPoints({});setCanvasMenu(null);setStyleOpen(false)}
 function restore(state){setProject(state.project);setScope(state.scope);setPath(state.path);setFrame(state.frame);setPosition(state.frame);setSceneTime(frameStart(timelineOf(state.project,state.scope).frames,state.frame,timelineOf(state.project,state.scope).duration));setZoom(state.zoom);setPan(state.pan);clearSelection();setPlaying(false);setTouchPreview(null)}
 function applyDocument(saved){camera.close();setPlaying(false);setVoiceMode(false);setVoicePaused(false);setRecordedMovie(null);setExportOpen(false);setSettings(false);setLocksOpen(false);setProjectError('');setDownloadError('');setClipboard(null);clearSelection();setTool('select');setTouchPreview(null);setSnapHint(null);gesture.current=null;pointers.current.clear();clearTimeout(wheelTimer.current);lastTap.current=null;
  const p=saved.preferences,e=saved.editor;setProject(saved.project);setScope(e.scope);setPath(e.path);setFrame(e.frame);setPosition(e.frame);setSceneTime(frameStart(timelineOf(saved.project,e.scope).frames,e.frame,timelineOf(saved.project,e.scope).duration));setZoom(e.zoom);setPan(e.pan);setDrawingStyle(p.drawingStyle);setSnap(p.snap);setGrid(p.grid);setMovieFps(p.movieFps);storage.resume();
 }
 function newProject(){setNewOpen(false);loadRequest.current++;remember();applyDocument({project:{frames:structuredClone(initialFrames),symbols:{},duration:1,easing:DEFAULT_EASING},preferences:{snap:true,grid:true,loop:true,movieFps:30,drawingStyle:{...DEFAULT_STYLE}},editor:{scope:null,path:[],frame:0,zoom:1,pan:{x:0,y:0}}})}
 async function loadJson(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;const request=++loadRequest.current;try{const saved=parseAnimation(await file.text());if(request!==loadRequest.current)return;remember();applyDocument(saved)}catch{if(request===loadRequest.current)setProjectError('This file could not be loaded as an animation. Your current project is unchanged.')}}
 async function importFiles(e){const files=[...(e.target.files||[])];e.target.value='';if(!files.length)return;const target=importTarget.current;if(!target)return;setImportOpen(false);setImportBusy(true);setProjectError('');const request=++loadRequest.current;
  try{const images=[],animations=[];for(const file of files){if(/\.json$/i.test(file.name)||file.type==='application/json')animations.push(parseAnimation(await file.text()));else images.push(await importImageFile(file))}
   if(request!==loadRequest.current)return;const current=projectRef.current,targetTimeline=timelineOf(current,target.scope),index=targetTimeline?.frames.findIndex(f=>f.id===target.frameId);if(index==null||index<0)throw new Error('The destination frame is no longer available.');
   const point=target.point||{x:0,y:0},shapes=[],definitions={},time=frameStart(targetTimeline.frames,index,targetTimeline.duration);let offset=0;
   for(const image of images){shapes.push(importedImage(image,{x:point.x+offset,y:point.y+offset},{w:size.w*.7/scale,h:size.h*.7/scale},uid));offset+=24/scale}
   for(const saved of animations){await preloadImages(saved.project);const imported=importedAnimation(saved,{x:point.x+offset,y:point.y+offset},time,uid);shapes.push(...imported.shapes);Object.assign(definitions,imported.symbols);offset+=24/scale}
   if(request!==loadRequest.current)return;const top=Math.max(-1,...resolveShapes(targetTimeline.frames,index).map((s,i)=>s.z??i));shapes.forEach((s,i)=>s.z=top+i+1);remember();setProject(p=>updateTimeline({...p,symbols:{...p.symbols,...definitions}},target.scope,{frames:timelineOf(p,target.scope).frames.map((f,i)=>i===index?{...f,changes:{...f.changes,...Object.fromEntries(shapes.map(s=>[s.id,s]))}}:f)}));setSelected(shapes.map(s=>s.id));setSelectedPoints({});setTool('select');notifyCopy('Imported');
  }catch(error){setProjectError(error.message||'The file could not be imported.')}finally{setImportBusy(false)}
 }
 function linkedCopy(){if(symbolShapes.length===selectedShapes.length&&symbolShapes.length){setClipboard({...copyLinkedShapes(symbolShapes),sourceScope:scope,sourceFrame:frames[frame].id});notifyCopy('Copied linked')}}
 function toggleLock(){patchMany(Object.fromEntries(selectedShapes.map(s=>[s.id,{locked:true}])));clearSelection()}
 function updateStyle(property,value){const normalized=property==='stroke'?Math.max(0,Math.min(80,Number(value)||0)):value;setDrawingStyle(s=>({...s,[property]:normalized}));patchMany(styleSelection(property==='fill'?styleShapes.filter(s=>s.type!=='line'):styleShapes,property,normalized))}
 function localBounds(s){return s.type==='symbol'?symbolLocalBounds(s,project.symbols,sceneTime):{left:0,top:0,right:s.w,bottom:s.h}}
 function resetCamera(){clearTimeout(wheelTimer.current);setZoom(1);setPan({x:0,y:0});setTouchPreview(null);setSnapHint(null)}
 function patchMany(changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:Object.fromEntries([...new Set([...Object.keys(f.changes),...Object.keys(changes)])].map(id=>[id,{...f.changes[id],...changes[id]}]))}:f))}
 function patch(id,changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:{...f.changes,[id]:{...f.changes[id],...changes}}}:f))}
 function undo(){if(!history.length)return;setFuture(f=>[...f,snapshot()]);setHistory(h=>h.slice(0,-1));restore(history.at(-1))}
 function redo(){if(!future.length)return;setHistory(h=>[...h,snapshot()]);setFuture(f=>f.slice(0,-1));restore(future.at(-1))}
 function chooseFrame(i){setPlaying(false);setFrame(i);setPosition(i);setSceneTime(frameStart(frames,i,duration));setSnapHint(null);clearSelection()}
 function addFrame(){remember();const next=[...frames];next.splice(frame+1,0,{id:uid(),changes:{}});setFrames(next);chooseFrame(frame+1)}
 function removeFrame(index=frame){if(frames.length<2)return;remember();setFrames(deleteFrame(frames,index));chooseFrame(Math.max(0,index-1));setSelected([])}
 function copyFrame(index){remember();const next=[...frames];next.splice(index+1,0,{...frames[index],id:uid(),changes:structuredClone(frames[index].changes)});setFrames(next);chooseFrame(index+1);setSelected([]);notifyCopy('Frame copied')}
 function reorderFrame(from,to){if(from===to)return;remember();setFrames(reorderFrames(frames,from,to));chooseFrame(to);setSelected([])}
 function deleteShape(){if(selectedShapes.length){patchMany(Object.fromEntries(selectedShapes.map(s=>[s.id,{visible:false}])));clearSelection()}}
 function copySelection(){if(selectedShapes.length){setClipboard({...copyShapes(selectedShapes,project.symbols),sourceScope:scope,sourceFrame:frames[frame].id});notifyCopy('Copied')}}
 function pasteSelection(){if(!clipboard)return;let copies;try{copies=pasteShapes(clipboard,uid,clipboard.sourceScope===scope&&clipboard.sourceFrame===frames[frame].id?spacing:0,frameStart(frames,frame,duration),{symbols:project.symbols,scope})}catch(error){setProjectError(error.message);setCanvasMenu(null);return}const top=Math.max(-1,...shapes.map((s,i)=>s.z??i));copies.shapes.forEach((s,i)=>s.z=top+i+1);setCanvasMenu(null);remember();setProject(p=>{const fs=timelineOf(p,scope).frames.map((f,i)=>i===frame?{...f,changes:{...f.changes,...Object.fromEntries(copies.shapes.map(s=>[s.id,s]))}}:f);return updateTimeline({...p,symbols:{...p.symbols,...copies.symbols}},scope,{frames:fs})});setSelected(copies.shapes.map(s=>s.id));setSelectedPoints({});setTool('select')}
 function makeSymbol(){if(shape?.type==='symbol'){const broken=breakSymbol(frames,frame,shape,project.symbols,uid,sceneTime);if(!broken)return;remember();setFrames(broken.frames);setSelected(broken.graphics.filter(s=>!s.locked).map(s=>s.id));setSelectedPoints({});setStyleOpen(false);return}const grouped=groupIntoSymbol(frames,frame,selectedShapes.map(s=>s.id),uid,duration,easing,project.symbols);if(!grouped)return;remember();setProject(p=>updateTimeline({...p,symbols:{...p.symbols,[grouped.definition.id]:grouped.definition}},scope,{frames:grouped.frames}));setSelected([grouped.instance.id]);setSelectedPoints({});setTool('select')}
 function enterSymbol(instance){if(!project.symbols[instance.symbolId])return;setPath(p=>[...p,{scope,frame,zoom,pan,instanceId:instance.id}]);setScope(instance.symbolId);setFrame(0);setPosition(0);setSceneTime(0);setPlaying(false);clearSelection();clearTimeout(wheelTimer.current);const camera=centerCamera(size,baseScale,selectionBounds(resolveShapes(project.symbols[instance.symbolId].frames,0),{symbols:project.symbols,time:0}));setZoom(camera.zoom);setPan(camera.pan);setTouchPreview(null);setSnapHint(null);lastTap.current=null}
 const parentEntry=path.at(-1),parentCandidates=scope&&parentEntry?resolveShapes(timelineOf(project,parentEntry.scope).frames,parentEntry.frame).filter(s=>s.symbolId===scope):[],currentInstance=parentEntry?.instanceId|| (parentCandidates.length===1?parentCandidates[0].id:null),sharedSymbol=!!scope&&!!currentInstance&&symbolIsShared(project,scope);
 function unlinkCurrentSymbol(){if(!sharedSymbol)return;const result=unlinkSymbolInstance(project,parentEntry.scope,currentInstance,scope,uid);if(!result)return;remember();setProject(result.project);setScope(result.scope);setPath(p=>p.map((entry,i)=>i===p.length-1?{...entry,instanceId:currentInstance}:entry));clearSelection();notifyCopy('Symbol unlinked')}
 function changeFrameTiming(index,timeMultiplier){remember();const next=frames.map((f,i)=>i===index?{...f,timeMultiplier}:f);setFrames(next);setSceneTime(frameStart(next,frame,duration));setPlaying(false)}
 function exitSymbol(){const parent=path.at(-1);if(!parent)return;setPath(p=>p.slice(0,-1));setScope(parent.scope);setFrame(parent.frame);setPosition(parent.frame);setSceneTime(frameStart(timelineOf(project,parent.scope).frames,parent.frame,timelineOf(project,parent.scope).duration));setZoom(parent.zoom);setPan(parent.pan);setPlaying(false);clearSelection()}
 function changeOrder(direction){const changes=reorderSelection(shapes,selectedShapes.map(s=>s.id),direction);if(Object.keys(changes).length)patchMany(changes)}

 function togglePlay(){if(playing){setPlaying(false);setFrame(Math.min(frames.length-1,Math.round(position)));return}if(!canPlay)return;const start=!loop&&frame===frames.length-1?0:frame;setPosition(start);setSceneTime(frameStart(frames,start,duration));clearSelection();setPlaying(true)}
 function enterVoice(){setPlaying(false);clearSelection();voiceTime.current=frameStart(frames,frame,duration);setTouchPreview(null);setSnapHint(null);setPosition(frame);voiceScene.current=resolveShapes(frames,frame);voiceTween.current=null;setVoicePaused(false);setVoiceMode(true)}
 function voiceFrame(target){voiceTween.current={from:voiceScene.current,to:resolveShapes(framesRef.current,target),elapsed:0,duration:frameSeconds(framesRef.current[target],duration)};setFrame(target)}
 function finishVoice(movie){camera.close();voiceTween.current=null;setVoiceMode(false);setVoicePaused(false);setPosition(frame);setSceneTime(voiceTime.current);if(movie)setRecordedMovie(movie)}
 useEffect(()=>{if(!voiceMode||voicePaused)return;let raf,last=performance.now();const tick=now=>{voiceTime.current+=(now-last)/1000;const tween=voiceTween.current;if(tween){tween.elapsed+=now-last;const t=Math.min(1,tween.elapsed/(tween.duration*1000));voiceScene.current=interpolateScene(tween.from,tween.to,t,easing);if(t===1)voiceTween.current=null}renderScene.current?.();last=now;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[voiceMode,voicePaused,duration,easing]);
 useEffect(()=>{const ro=new ResizeObserver(([entry])=>setSize({w:entry.contentRect.width,h:entry.contentRect.height,orientation:window.innerWidth>=window.innerHeight?'landscape':'portrait'}));ro.observe(stageRef.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{
  const canvas=canvasRef.current;
  const wheel=e=>{e.preventDefault();if(voiceModeRef.current)return;const v=viewRef.current,r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;
   const nextZoom=Math.max(.4,Math.min(MAX_ZOOM,v.zoom*Math.exp(-e.deltaY*.002))),nextScale=v.baseScale*nextZoom;
   const world={x:(x-v.origin.x)/v.scale,y:(y-v.origin.y)/v.scale};
   const nextPan={x:x-world.x*nextScale,y:y-world.y*nextScale};
   setZoom(nextZoom);setPan(nextPan);viewRef.current={...v,zoom:nextZoom,pan:nextPan,scale:nextScale,origin:{...nextPan}};
   clearTimeout(wheelTimer.current);wheelTimer.current=setTimeout(()=>{const latest=viewRef.current;if(latest.snap){const aligned=alignCamera(latest.size,latest.baseScale,latest.zoom,latest.pan);setZoom(aligned.zoom);setPan(aligned.pan)}},160);
  };
  canvas.addEventListener('wheel',wheel,{passive:false});return()=>{canvas.removeEventListener('wheel',wheel);clearTimeout(wheelTimer.current)};
 },[]);

 useEffect(()=>{if(!playing)return;let raf,last=performance.now(),t=sceneTime;const tick=now=>{t+=(now-last)/1000;last=now;setPosition(timelinePosition(frames,t,duration));setSceneTime(t);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing,duration,frames]);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(storage.ready)saveJson();return}if(e.target.closest('input,select,textarea,.camera-window,.mini-menu,.frame-card')||settings||exportOpen||voiceMode||recordedMovie||styleOpen||locksOpen||newOpen||importOpen||importBusy)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&['c','v'].includes(e.key.toLowerCase())){e.preventDefault();e.key.toLowerCase()==='c'?copySelection():pasteSelection();return}if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteShape()}else if(e.key==='Escape'){clearSelection();setPlaying(false)}else if(e.key==='ArrowRight')chooseFrame(Math.min(frames.length-1,frame+1));else if(e.key==='ArrowLeft')chooseFrame(Math.max(0,frame-1));else if(e.key.toLowerCase()==='n')addFrame();else{const t=toolList.find(t=>t[3].toLowerCase()===e.key.toLowerCase());if(t){setPlaying(false);setTool(t[0])}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 useEffect(()=>{if(!settings)return;settingsRef.current?.querySelector('button')?.focus();const onKey=e=>{if(e.key==='Escape')setSettings(false);if(e.key==='Tab'){const els=[...settingsRef.current.querySelectorAll('button:not(:disabled),input,select')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('keydown',onKey);settingsButtonRef.current?.focus()}},[settings]);
 useEffect(()=>{if(!canvasMenu)return;const close=e=>{if(!e.target.closest('.canvas-menu,.main-canvas'))setCanvasMenu(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[canvasMenu]);
 const toWorld=p=>{const r=canvasRef.current.getBoundingClientRect();return{x:(p.clientX-r.left-origin.x)/scale,y:(p.clientY-r.top-origin.y)/scale}};
 const snapped=p=>snap?{x:Math.round(p.x/spacing)*spacing,y:Math.round(p.y/spacing)*spacing}:p;
 function endpoint(p,id){const result=snapEndpoint(resolveShapes(framesRef.current,frame),p,id,scale,snap,spacing);setSnapHint(snap?result.point:null);return result}
 function showTouch(e,p){if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const r=canvasRef.current.getBoundingClientRect();setTouchPreview({x:e.clientX-r.left,y:e.clientY-r.top,world:p})}
 function hit(p,s){if(s.locked)return false;const q=worldToLocal(s,p),pad=14/scale;if(s.type==='circle')return((q.x-s.w/2)/(Math.abs(s.w/2)+pad))**2+((q.y-s.h/2)/(Math.abs(s.h/2)+pad))**2<=1;if(s.type==='rect'||s.type==='image'||s.type==='symbol'){const b=localBounds(s);return q.x>=b.left-pad&&q.y>=b.top-pad&&q.x<=b.right+pad&&q.y<=b.bottom+pad}for(let t=0;t<=1;t+=1/Math.max(70,(s.path?.length||0)*8)){const point=linePoint(s,t);if(Math.hypot(p.x-point.x,p.y-point.y)<pad+s.stroke)return true}return false}
 function pointerDown(e){if(!storage.ready||voiceMode||importBusy||e.button>1)return;setCanvasMenu(null);setStyleOpen(false);setManipulating(true);e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pointers.current.size===2){const ps=[...pointers.current.values()],g=gesture.current;if(g?.beforeProject){setProject(g.beforeProject);setHistory(h=>h.slice(0,g.historyLength))}const center={clientX:(ps[0].clientX+ps[1].clientX)/2,clientY:(ps[0].clientY+ps[1].clientY)/2};gesture.current={type:'pinch',distance:Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),zoom,world:toWorld(center)};setSnapHint(null);setTouchPreview(null);setMarquee(null);if(g?.selected){setSelected(g.selected);setSelectedPoints(g.points)}return}if(playing||pointers.current.size>1)return;
 const p=toWorld(e),baseline={beforeProject:project,historyLength:history.length,selected:[...selected],points:structuredClone(selectedPoints),hadCanvasMenu:!!canvasMenu};if(e.button===1){gesture.current={type:'pan',start:{x:e.clientX,y:e.clientY},pan};return}
 if(tool==='select'){
  if(bounds&&isGroupSelection(selected,selectedPoints)){const controls=selectionControls(bounds,scale),handle=controls.corners.find(h=>Math.hypot(p.x-h.x,p.y-h.y)*scale<16),rotate=Math.hypot(p.x-controls.handle.x,p.y-controls.handle.y)*scale<20;if(handle||rotate){gesture.current={...baseline,type:rotate?'group-rotate':'group-scale',start:p,shape:selectedShapes[0],shapes,ids:selected,points:selectedPoints,controls,corner:handle?.key,center:controls.center,angle:Math.atan2(p.y-controls.center.y,p.x-controls.center.x),delta:0,moved:false};return}}
  if(shape){const control=rotationControl(shape,scale,{symbols:project.symbols,time:sceneTime});if(Math.hypot(p.x-control.handle.x,p.y-control.handle.y)*scale<20){gesture.current={...baseline,type:'rotate',start:p,shape:{...shape},center:control.center,angle:rotationAngle(shape,control.center,p),delta:0,moved:false};return}}
  if(!e.shiftKey&&isGroupSelection(selected,selectedPoints)){const first=shapes.find(s=>!s.locked&&selected.includes(s.id)),anchor=first?localToWorld(first,{x:0,y:0}):{x:bounds.left,y:bounds.top};gesture.current={...baseline,type:'move',start:p,shape:selectedShapes[0],shapes,ids:selected,points:selectedPoints,anchor,moved:false,group:true,tapTarget:[...shapes].reverse().find(s=>hit(p,s))?.id,emptyTap:!shapes.some(s=>hit(p,s))};return}

  const node=[...shapes].reverse().filter(s=>!s.locked&&s.type==='line'&&(selected.includes(s.id)||selectedPoints[s.id]?.length)).flatMap(s=>Object.entries(lineHandles(s)).map(([key,point])=>({shape:s,key,point,distance:Math.hypot(p.x-point.x,p.y-point.y)*scale}))).filter(n=>n.distance<12).sort((a,b)=>a.distance-b.distance)[0];
  if(node){setDrawingStyle(old=>({...old,color:node.shape.color,strokeColor:node.shape.strokeColor||node.shape.color,stroke:node.shape.stroke,strokeStyle:node.shape.strokeStyle||'solid',strokeVisible:node.shape.strokeVisible!==false}));let ids=selected,points=selectedPoints;const already=points[node.shape.id]?.includes(node.key)&&!ids.includes(node.shape.id);if(!already){ids=e.shiftKey?ids:[];points=mergePoints(e.shiftKey?points:{},{[node.shape.id]:[node.key]})}else if(e.shiftKey){points={...points,[node.shape.id]:points[node.shape.id].filter(k=>k!==node.key)};if(!points[node.shape.id].length)delete points[node.shape.id];setSelectedPoints(points);return}setSelected(ids);setSelectedPoints(points);const single=!ids.length&&Object.values(points).flat().length===1;gesture.current={...baseline,type:'points',start:p,anchor:node.point,key:node.key,shape:node.shape,shapes,ids,points,single,moved:false};return}
  if(shape&&shape.type!=='line'&&!e.shiftKey&&!(shape.type==='symbol'&&lastTap.current?.id===shape.id&&performance.now()-lastTap.current.time<350)){const q=worldToLocal(shape,p),b=localBounds(shape),handles=[{x:b.left,y:b.top,key:'scale-tl'},{x:b.right,y:b.top,key:'scale-tr'},{x:b.left,y:b.bottom,key:'scale-bl'},{x:b.right,y:b.bottom,key:'scale-br'}],h=handles.find(h=>Math.hypot(q.x-h.x,q.y-h.y)<16/scale);if(h){gesture.current={...baseline,type:h.key,start:p,shape:{...shape},localBounds:b,moved:false};return}}
  const target=[...shapes].reverse().find(s=>hit(p,s));
  if(target){const ids=e.shiftKey?(selected.includes(target.id)?selected.filter(id=>id!==target.id):[...selected,target.id]):selected.includes(target.id)?selected:[target.id],points=e.shiftKey||selected.includes(target.id)?selectedPoints:{};setSelected(ids);setSelectedPoints(points);if(ids.length===1&&target.type!=='symbol'&&target.type!=='image')setDrawingStyle(old=>({...old,color:target.color,strokeColor:target.strokeColor||target.color,stroke:target.stroke,strokeStyle:target.strokeStyle||'solid',strokeVisible:target.strokeVisible!==false,...(target.type!=='line'?{fill:!!target.fill}:{})}));if(ids.includes(target.id))gesture.current={...baseline,type:'move',start:p,shape:{...target},shapes,ids,points,moved:false,tapTarget:e.shiftKey?null:target.id};return}
  const base=e.shiftKey?selected:[],basePoints=e.shiftKey?selectedPoints:{};setSelected(base);setSelectedPoints(basePoints);setMarquee({start:p,end:p});gesture.current={...baseline,type:'box',start:p,base,basePoints,hadSelection:selectedShapes.length>0,moved:false};return;
 }
 if(tool==='brush'){const id=uid(),s={id,type:'line',lineKind:'brush',name:'Brush',z:Math.max(-1,...shapes.map((s,i)=>s.z??i))+1,...newShapeStyle('line',drawingStyle),opacity:1,visible:true,...brushGeometry([p])};remember();patch(id,s,false);setSelected([id]);setSelectedPoints({});gesture.current={...baseline,type:'brush',start:p,shape:s,samples:[p]};showTouch(e,p);return}
 const type=tool==='bezier'?'line':tool,id=uid(),connection=type==='line'?endpoint(p,id):{point:snapped(p),link:null},start=connection.point,s={id,type,lineKind:tool==='line'?'straight':'bezier',z:Math.max(-1,...shapes.map((s,i)=>s.z??i))+1,name:type==='rect'?'Square':type==='circle'?'Circle':tool==='bezier'?'Bézier line':'Straight line',x:start.x,y:start.y,w:0,h:0,cx:0,cy:0,...newShapeStyle(type,drawingStyle),opacity:1,rotation:0,visible:true,startLink:null,endLink:null};if(type==='line')showTouch(e,p);remember();patch(id,s,false);setSelected([id]);setSelectedPoints({});gesture.current={...baseline,type:'draw',start,shape:s};
 }
 function pointerMove(e){if(pointers.current.has(e.pointerId))pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});const g=gesture.current;if(!g)return;if(g.type==='pinch'){const ps=[...pointers.current.values()];if(ps.length!==2)return;const distance=Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),nextZoom=Math.max(.4,Math.min(MAX_ZOOM,g.zoom*distance/Math.max(1,g.distance))),nextScale=baseScale*nextZoom,r=canvasRef.current.getBoundingClientRect(),center={x:(ps[0].clientX+ps[1].clientX)/2-r.left,y:(ps[0].clientY+ps[1].clientY)/2-r.top};const nextPan={x:center.x-g.world.x*nextScale,y:center.y-g.world.y*nextScale};g.camera={zoom:nextZoom,pan:nextPan};setZoom(nextZoom);setPan(nextPan);return}if(g.type==='pan'){setPan({x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y});return}
 const raw=toWorld(e),p=snapped(raw),s=g.shape,dx=raw.x-g.start.x,dy=raw.y-g.start.y;
 if(g.type==='brush'){showTouch(e,raw);const events=e.getCoalescedEvents?.()||[];for(const event of events.length?events:[e]){const point=toWorld(event),last=g.samples.at(-1);if(Math.hypot(point.x-last.x,point.y-last.y)*scale>=5)g.samples.push(point)}if(g.samples.length>1200)g.samples=g.samples.filter((_,i)=>i%2===0);patch(s.id,brushGeometry([...g.samples,raw]),false);return}
 if(g.type==='group-rotate'||g.type==='group-scale'){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}if(g.type==='group-rotate'){const angle=Math.atan2(raw.y-g.center.y,raw.x-g.center.x);g.delta+=Math.atan2(Math.sin(angle-g.angle),Math.cos(angle-g.angle));g.angle=angle;let degrees=g.delta*180/Math.PI;if(e.shiftKey)degrees=Math.round(degrees/15)*15;g.handle=raw;patchMany(transformParts(g.shapes,g.ids,g.points,rotationMatrix(g.center,degrees),{center:g.center,degrees}),false)}else patchMany(transformParts(g.shapes,g.ids,g.points,selectionScale(g.controls.bounds,g.corner,p,e.shiftKey)),false);return}
 if(g.type==='rotate'){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}const angle=rotationAngle(s,g.center,raw);g.delta+=Math.atan2(Math.sin(angle-g.angle),Math.cos(angle-g.angle));g.angle=angle;const degrees=g.delta*180/Math.PI;g.handle=raw;patch(s.id,rotateShape(s,g.center,e.shiftKey?Math.round(degrees/15)*15:degrees),false);return}
 if(g.type==='box'){if(!g.moved&&Math.hypot(dx,dy)*scale<4)return;g.moved=true;const parts=boxSelectParts(shapes,g.start,raw,{symbols:project.symbols,time:sceneTime});setMarquee({start:g.start,end:raw});setSelected([...new Set([...g.base,...parts.ids])]);setSelectedPoints(mergePoints(g.basePoints,parts.points));return}
 if((g.type==='draw'&&s.type==='line')||(g.type==='points'&&g.single))showTouch(e,raw);
 if(g.type==='move'){if(!g.moved&&Math.hypot(dx,dy)*scale<4)return;if(!g.moved){remember();g.moved=true}const anchor=g.anchor||localToWorld(s,{x:0,y:0}),point=snapped({x:anchor.x+dx,y:anchor.y+dy});patchMany(moveParts(g.shapes,g.ids,g.points,point.x-anchor.x,point.y-anchor.y),false);return}
 if(g.type==='points'){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}if(g.single){if(s.lineKind==='brush'){const handles=lineHandles(s),point={x:g.anchor.x+dx,y:g.anchor.y+dy};handles[g.key]=Number(g.key.slice(1))%2?snapped(point):endpoint(point,s.id).point;patch(s.id,patchLineHandles(s,handles),false);return}const geometry=lineGeometry(s),point={x:g.anchor.x+dx,y:g.anchor.y+dy},target=g.key==='control'?{point:snapped(point)}:endpoint(point,s.id);geometry[g.key]=target.point;setSnapHint(snap?target.point:null);patch(s.id,{...linePatch(s,geometry.start,geometry.end,geometry.control),...(g.key==='control'?{}:{[g.key+'Link']:null})},false)}else{const point=snapped({x:g.anchor.x+dx,y:g.anchor.y+dy});patchMany(moveParts(g.shapes,g.ids,g.points,point.x-g.anchor.x,point.y-g.anchor.y),false)}return}
 if(g.type==='draw'){if(s.type==='line'){const target=endpoint(raw,s.id),end=target.point;patch(s.id,{...fromLinePoints(g.start,end,{x:(g.start.x+end.x)/2-(s.lineKind==='bezier'?(end.y-g.start.y)*.25:0),y:(g.start.y+end.y)/2+(s.lineKind==='bezier'?(end.x-g.start.x)*.25:0)}),endLink:null},false)}else{let w=p.x-g.start.x,h=p.y-g.start.y;if(e.shiftKey){const a=Math.max(Math.abs(w),Math.abs(h));w=Math.sign(w||1)*a;h=Math.sign(h||1)*a}patch(s.id,{x:Math.min(g.start.x,g.start.x+w),y:Math.min(g.start.y,g.start.y+h),w:Math.abs(w),h:Math.abs(h)},false)}}
 if(g.type.startsWith('scale-')){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}const q=worldToLocal(s,p),corner=g.type.slice(6),old=g.localBounds||{left:0,top:0,right:s.w,bottom:s.h};let{left,top,right,bottom}=old;
  const minW=Math.min(20,Math.max(1,(old.right-old.left)/5)),minH=Math.min(20,Math.max(1,(old.bottom-old.top)/5));if(corner[1]==='l')left=Math.min(q.x,right-minW);else right=Math.max(left+minW,q.x);if(corner[0]==='t')top=Math.min(q.y,bottom-minH);else bottom=Math.max(top+minH,q.y);
  if(e.shiftKey){const height=(right-left)*(old.bottom-old.top)/Math.max(1,old.right-old.left);if(corner[0]==='t')top=bottom-height;else bottom=top+height}
  const fx=(right-left)/Math.max(.001,old.right-old.left),fy=(bottom-top)/Math.max(.001,old.bottom-old.top),w=s.w*fx,h=s.h*fy,worldCenter=localToWorld(s,{x:left-old.left*fx+w/2,y:top-old.top*fy+h/2}),center=transformPoint(inverse(s.matrix),worldCenter);patch(s.id,{x:center.x-w/2,y:center.y-h/2,w,h},false)
 }

 }
 function pointerUp(e){pointers.current.delete(e.pointerId);setManipulating(false);setMarquee(null);const g=gesture.current;let enteredSymbol=false;if(g?.type==='pinch'&&snap){const camera=g.camera||{zoom,pan};const aligned=alignCamera(size,baseScale,camera.zoom,camera.pan);setZoom(aligned.zoom);setPan(aligned.pan)}if(g?.type==='brush'){if(e.type==='pointercancel'){setProject(g.beforeProject);setHistory(h=>h.slice(0,g.historyLength));setSelected(g.selected);setSelectedPoints(g.points)}else{const point=toWorld(e);patch(g.shape.id,brushGeometry([...g.samples,point]),false)}}if(g?.type==='draw'){const s=resolveShapes(framesRef.current,frame).find(s=>s.id===g.shape.id);if(s&&Math.abs(s.w)+Math.abs(s.h)<4)patch(s.id,{w:160,h:s.type==='line'?0:160,cx:80,cy:s.type==='line'?(s.lineKind==='bezier'?40:0):80,endLink:null},false);setTool('select')}if(e.type!=='pointercancel'&&!g?.group&&(g?.type==='move'||g?.type.startsWith('scale-'))&&!g.moved&&g.shape.type==='symbol'){const now=performance.now(),previous=lastTap.current;if(previous?.id===g.shape.id&&now-previous.time<350&&Math.hypot(e.clientX-previous.x,e.clientY-previous.y)<20){enterSymbol(g.shape);enteredSymbol=true}else lastTap.current={id:g.shape.id,time:now,x:e.clientX,y:e.clientY}}if(e.type!=='pointercancel'&&!enteredSymbol&&g?.type==='move'&&!g.moved&&g.tapTarget&&(g.selected.includes(g.tapTarget)||g.points[g.tapTarget]?.length)){setSelected(g.selected.filter(id=>id!==g.tapTarget));setSelectedPoints(Object.fromEntries(Object.entries(g.points).filter(([id])=>id!==g.tapTarget)))}if(e.type!=='pointercancel'&&g?.group&&!g.moved&&g.emptyTap)clearSelection();if(e.type!=='pointercancel'&&g?.type==='box'&&!g.moved&&!g.hadSelection&&!g.hadCanvasMenu){const r=canvasRef.current.getBoundingClientRect();setCanvasMenu({x:Math.max(8,Math.min(size.w-232,e.clientX-r.left-116)),y:Math.max(8,Math.min(size.h-60,e.clientY-r.top-76)),world:toWorld(e)})}gesture.current=null;setSnapHint(null);setTouchPreview(null)}
 useEffect(()=>{const draw=()=>{const canvas=canvasRef.current,ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(size.w*dpr)||canvas.height!==Math.round(size.h*dpr)){canvas.width=Math.round(size.w*dpr);canvas.height=Math.round(size.h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size.w,size.h);
 if(grid)drawGrid(ctx,size.w,size.h,scale,origin,level);
 ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(scale,scale);const rendered=voiceMode?voiceScene.current:playing?interpolateShapes(frames,position,easing,loop):shapes;rendered.forEach(s=>drawShape(ctx,s,{symbols:project.symbols,time:voiceMode?voiceTime.current:sceneTime}));
 if(!playing&&!voiceMode){
  for(const s of shapes.filter(s=>!s.locked&&s.type==='line'&&tool==='select'&&(selected.includes(s.id)||selectedPoints[s.id]?.length))){const geometry=lineGeometry(s),active=selected.includes(s.id)||selectedPoints[s.id]?.length;if(active&&s.lineKind!=='straight'&&s.lineKind!=='brush'){ctx.strokeStyle='#b6a1fb88';ctx.lineWidth=1/scale;ctx.setLineDash([4/scale,4/scale]);ctx.beginPath();ctx.moveTo(geometry.start.x,geometry.start.y);ctx.lineTo(geometry.control.x,geometry.control.y);ctx.lineTo(geometry.end.x,geometry.end.y);ctx.stroke();ctx.setLineDash([])}for(const[key,p]of Object.entries(lineHandles(s))){const picked=selected.includes(s.id)||selectedPoints[s.id]?.includes(key);ctx.beginPath();ctx.arc(p.x,p.y,(picked?5:3)/scale,0,Math.PI*2);ctx.fillStyle=picked?'#b6a1fb':'#25272d';ctx.strokeStyle=picked?'#c6b2ff':'#737080';ctx.lineWidth=1/scale;ctx.fill();ctx.stroke()}}
  for(const s of selectedShapes.filter(s=>s.type!=='line')){ctx.save();if(s.matrix)ctx.transform(...s.matrix);ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-s.w/2,-s.h/2);ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;const b=localBounds(s);ctx.strokeRect(b.left,b.top,b.right-b.left,b.bottom-b.top);if(shape)for(const[x,y]of[[b.left,b.top],[b.right,b.top],[b.left,b.bottom],[b.right,b.bottom]]){ctx.fillStyle='#202229';ctx.beginPath();ctx.arc(x,y,4/scale,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
 }
 if((shape||(bounds&&isGroupSelection(selected,selectedPoints)))&&tool==='select'&&!playing&&!voiceMode){const control=shape?rotationControl(shape,scale,{symbols:project.symbols,time:sceneTime},gesture.current?.type==='rotate'?gesture.current.handle:null):selectionControls(bounds,scale),{base}=control,handle=gesture.current?.type==='group-rotate'&&gesture.current.handle?gesture.current.handle:control.handle;ctx.strokeStyle='#b6a1fb';ctx.fillStyle='#202229';ctx.lineWidth=1.2/scale;ctx.beginPath();ctx.moveTo(base.x,base.y);ctx.lineTo(handle.x,handle.y);ctx.stroke();ctx.beginPath();ctx.arc(handle.x,handle.y,10/scale,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(handle.x,handle.y,4.5/scale,-Math.PI*.8,Math.PI*.7);ctx.stroke();ctx.beginPath();ctx.moveTo(handle.x-5/scale,handle.y-4/scale);ctx.lineTo(handle.x-1/scale,handle.y-4/scale);ctx.lineTo(handle.x-2/scale,handle.y);ctx.stroke()}
 if(bounds&&(selectedShapes.length>1||Object.values(selectedPoints).flat().length>1)&&!playing&&!voiceMode){ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;ctx.setLineDash([5/scale,4/scale]);ctx.strokeRect(bounds.left-8/scale,bounds.top-8/scale,bounds.right-bounds.left+16/scale,bounds.bottom-bounds.top+16/scale);ctx.setLineDash([]);for(const h of selectionControls(bounds,scale).corners){ctx.fillStyle='#202229';ctx.beginPath();ctx.arc(h.x,h.y,5/scale,0,Math.PI*2);ctx.fill();ctx.stroke()}}
 if(snapHint){ctx.strokeStyle='#b4d7a0';ctx.lineWidth=2/scale;ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,11/scale,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b4d7a0';ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,3/scale,0,Math.PI*2);ctx.fill()}ctx.restore();
 };renderScene.current=draw;draw();return()=>{renderScene.current=null}},[project,frames,frame,selected,selectedPoints,position,sceneTime,playing,size,zoom,pan,grid,easing,loop,snapHint,voiceMode,tool,manipulating,imageVersion]);
 const menuWidth=Math.min(486,size.w-16),menuX=bounds?Math.max(8,Math.min(size.w-menuWidth-8,origin.x+(bounds.left+bounds.right)*scale/2-menuWidth/2)):8;
 const menuY=Math.max(8,Math.min(size.h-60,bounds?origin.y+bounds.top*scale-94:8));
 return <main className="editor" aria-busy={!storage.ready} inert={!storage.ready}><section className="stage" ref={stageRef}><canvas className={`main-canvas tool-${tool}`} ref={canvasRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} aria-label="Animation drawing canvas"/>{touchPreview&&<TouchPreview touch={touchPreview} size={size} scale={scale} shapes={shapes} selected={gesture.current?.shape?.id} grid={grid} hint={snapHint} level={level} symbols={project.symbols} time={sceneTime}/>}{marquee&&<div className="selection-box" style={{left:origin.x+Math.min(marquee.start.x,marquee.end.x)*scale,top:origin.y+Math.min(marquee.start.y,marquee.end.y)*scale,width:Math.abs(marquee.end.x-marquee.start.x)*scale,height:Math.abs(marquee.end.y-marquee.start.y)*scale}}/>}
 {selectedShapes.length>0&&!playing&&!voiceMode&&!manipulating&&!settings&&!exportOpen&&!recordedMovie&&<div className="mini-menu shape-menu" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();clearSelection()}}} role="toolbar" aria-label={selectedShapes.length===1?'Shape actions':`${selectedShapes.length} selected shapes`} style={{left:menuX,top:menuY,maxWidth:menuWidth}}>
 {symbolShapes.length>0&&<label className="menu-color tint-color" title="Symbol tint (white keeps original colors)"><span style={{background:symbolShapes[0].tint||'#ffffff'}}/><input type="color" aria-label="Symbol tint" value={symbolShapes[0].tint||'#ffffff'} onChange={e=>patchMany(styleSelection(symbolShapes,'tint',e.target.value))}/></label>}
 {styleShapes.length>0&&<><label className="menu-color" title="Fill color"><span style={{background:styleShapes[0].color}}/><input type="color" aria-label="Fill color" value={styleShapes[0].color} onChange={e=>updateStyle('color',e.target.value)}/></label><label className="menu-color stroke-color" title="Stroke color"><span style={{borderColor:styleShapes[0].strokeColor||styleShapes[0].color}}/><input type="color" aria-label="Stroke color" value={styleShapes[0].strokeColor||styleShapes[0].color} onChange={e=>updateStyle('strokeColor',e.target.value)}/></label><IconButton icon={SlidersHorizontal} label="Style options" active={styleOpen} onClick={()=>setStyleOpen(!styleOpen)}/></>}
 <IconButton icon={Copy} label="Copy selected shapes" onClick={copySelection}/>{symbolShapes.length===selectedShapes.length&&<IconButton icon={Link2} label="Copy linked symbols" onClick={linkedCopy}/>}<IconButton icon={Group} active={shape?.type==='symbol'} label={shape?.type==='symbol'?'Break apart symbol':'Create symbol'} onClick={makeSymbol}/><IconButton icon={Lock} label="Lock selected objects" onClick={toggleLock}/><IconButton icon={ArrowUp} label="Bring forward" onClick={()=>changeOrder('up')}/><IconButton icon={ArrowDown} label="Send backward" onClick={()=>changeOrder('down')}/><IconButton icon={Trash2} label="Delete selected shapes" onClick={deleteShape}/></div>}
 {canvasMenu&&!voiceMode&&!playing&&!manipulating&&<div className="mini-menu canvas-menu" role="toolbar" aria-label="Canvas actions" style={{left:canvasMenu.x,top:canvasMenu.y}}><button disabled={!clipboard} onClick={pasteSelection}><ClipboardPaste size={18}/><span>Paste</span></button><button onClick={()=>{importTarget.current={scope,frameId:frames[frame].id,point:canvasMenu.world};setCanvasMenu(null);setImportOpen(true)}}><Import size={18}/><span>Import</span></button></div>}
 {copyNotice&&<div className="copy-notice" role="status" key={copyNotice.id}>{copyNotice.text}</div>}
 {scope&&!voiceMode&&<div className="symbol-navigation"><button className="symbol-exit" onClick={exitSymbol} aria-label="Exit symbol"><LogOut size={16}/><span>Exit symbol{path.length>1?` · ${path.length}`:''}</span></button>{sharedSymbol&&<IconButton icon={Link2} label="Unlink this symbol" active onClick={unlinkCurrentSymbol}/>}</div>}
 {(storage.message||downloadError||projectError)&&<div className="storage-notice" role="alert"><span>{projectError||downloadError||storage.message}</span><button onClick={saveJson}>Save JSON</button><IconButton icon={X} label="Dismiss save message" onClick={()=>{storage.dismiss();setDownloadError('');setProjectError('')}}/></div>}
 <CameraOverlay camera={camera} size={size}/></section>
 <div className="controls">{voiceMode?<Voiceover getRecordingScene={getRecordingScene} camera={camera} canvasRef={canvasRef} fps={movieFps} orientation={size.orientation} onPaused={setVoicePaused} onDone={finishVoice} onExport={()=>setExportOpen(true)}/>:<div className="tool-row"><div className="undo-tools" aria-label="History and playback"><IconButton icon={Undo2} label="Undo (⌘Z)" disabled={!history.length} onClick={undo}/><IconButton icon={Redo2} label="Redo (⌘⇧Z)" disabled={!future.length} onClick={redo}/><IconButton icon={playing?Pause:Play} label={playing?'Pause (Space)':'Play (Space)'} className="play-button" disabled={!canPlay} onClick={togglePlay}/></div><nav className="tool-scroll" aria-label="Drawing tools and settings">{toolList.map(([id,Icon,label,key])=><span className="tool-pair" key={id}><IconButton icon={Icon} label={`${label} (${key})`} active={tool===id} onClick={()=>{setCanvasMenu(null);setPlaying(false);setTool(id)}}/>{id==='select'&&<IconButton icon={Magnet} label="Snap to grid and shapes" active={snap} onClick={()=>setSnap(!snap)}/>}</span>)}<span className="separator"/><IconButton icon={Focus} label="Reset camera" onClick={resetCamera}/>{scope&&<IconButton icon={LogOut} label="Exit symbol" onClick={exitSymbol}/>}<IconButton icon={Film} label="Recording area" onClick={enterVoice}/><IconButton icon={FileDown} label="Save animation as JSON (⌘S)" onClick={saveJson}/><IconButton icon={FolderOpen} label="Load animation JSON" onClick={()=>loadInput.current?.click()}/><IconButton icon={FilePlus2} label="New project" onClick={()=>{setPlaying(false);setNewOpen(true)}}/>{lockedShapes.length>0&&<IconButton icon={Unlock} label="Locked objects" onClick={()=>setLocksOpen(true)}/>}<button ref={settingsButtonRef} className="icon-button" aria-label="Settings" title="Settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></nav></div>}
 <FrameTimeline key={scope||'main'} symbols={project.symbols} duration={duration} frames={frames} frame={frame} playing={playing} position={position} recording={voiceMode} onChoose={voiceMode?voiceFrame:chooseFrame} onAdd={addFrame} onCopy={copyFrame} onDelete={removeFrame} onReorder={reorderFrame} onTiming={changeFrameTiming}/></div>
 {importBusy&&<div className="import-progress" role="status">Importing…</div>}
 {importOpen&&<EditorDialog title="Import" onClose={()=>setImportOpen(false)}><button className="import-choice" onClick={()=>photoInput.current?.click()}><ImagePlus size={20}/><span>Photo library</span></button><button className="import-choice" onClick={()=>importInput.current?.click()}><FolderOpen size={20}/><span>Files · images or animation JSON</span></button></EditorDialog>}
 <input ref={photoInput} className="hidden-file-input" type="file" accept="image/*" multiple aria-label="Import photos" onChange={importFiles}/>
 <input ref={importInput} className="hidden-file-input" type="file" accept="image/*,.json,application/json" multiple aria-label="Import images or saved animations" onChange={importFiles}/>
 <input ref={loadInput} className="hidden-file-input" type="file" accept=".json,application/json" aria-label="Load animation file" onChange={loadJson}/>
 {styleOpen&&styleShapes.length>0&&<EditorDialog title="Style" onClose={()=>setStyleOpen(false)}><label className="settings-row"><span>Filled</span><input type="checkbox" disabled={styleShapes.every(s=>s.type==='line')} checked={styleShapes.every(s=>s.type==='line'||s.fill)} onChange={e=>updateStyle('fill',e.target.checked)}/></label><label className="settings-row"><span>Stroke</span><input type="checkbox" checked={styleShapes.every(s=>s.strokeVisible!==false)} onChange={e=>updateStyle('strokeVisible',e.target.checked)}/></label><label className="settings-row"><span>Stroke width</span><StrokeWidthInput value={styleShapes[0].stroke} onCommit={value=>updateStyle('stroke',value)}/></label><label className="settings-row"><span>Stroke style</span><select value={styleShapes[0].strokeStyle||'solid'} onChange={e=>updateStyle('strokeStyle',e.target.value)}>{STROKE_STYLES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></EditorDialog>}
 {newOpen&&<EditorDialog title="New project?" onClose={()=>setNewOpen(false)}><p className="confirm-message">Clear the current animation and start a blank project?</p><div className="confirm-actions"><button className="done-button secondary" onClick={()=>setNewOpen(false)}>Cancel</button><button className="done-button" onClick={newProject}>Clear project</button></div></EditorDialog>}
 {locksOpen&&<EditorDialog title="Locked objects" onClose={()=>setLocksOpen(false)}>{lockedShapes.map(s=><div className="settings-row" key={s.id}><span>{s.name||s.type}</span><IconButton icon={Unlock} label={`Unlock ${s.name||s.type}`} onClick={()=>patch(s.id,{locked:false})}/></div>)}{!lockedShapes.length&&<p className="empty-locks">No locked objects</p>}</EditorDialog>}
 {exportOpen&&<MovieExport getCameraOverlay={camera.getOverlay} frames={frames} symbols={project.symbols} duration={duration} loop={loop} easing={easing} fps={movieFps} onFpsChange={setMovieFps} view={{width:size.w,height:size.h,orientation:size.orientation,scale,origin,gridLevel:level}} onClose={()=>setExportOpen(false)}/>}
 {recordedMovie&&<MovieSave recording={recordedMovie} onClose={()=>setRecordedMovie(null)}/>}
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><div ref={settingsRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><div className="modal-heading"><h2 id="settings-title">Settings</h2><IconButton icon={X} label="Close settings" onClick={()=>setSettings(false)}/></div><label className="settings-row"><span>Seconds between frames</span><input type="number" inputMode="decimal" min="0.1" max="30" step="0.1" value={duration} onChange={e=>setDuration(Math.max(.1,Math.min(30,+e.target.value||1)))}/></label><label className="settings-row"><span>Movie frame rate</span><select value={movieFps} onChange={e=>setMovieFps(Number(e.target.value))}>{MOVIE_FPS.map(fps=><option key={fps} value={fps}>{fps} fps</option>)}</select></label><label className="settings-row"><span>Transition</span><select value={easing} onChange={e=>setEasing(e.target.value)}><option value="smooth">Smooth</option><option value="linear">Linear</option></select></label><label className="settings-row"><span>Show grid</span><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/></label><label className="settings-row"><span>Snap to grid and shapes</span><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/></label><button className="done-button" onClick={()=>setSettings(false)}>Done</button></div></div>}
 </main>
}
