'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {MousePointer2,Minus,Circle,Square,Magnet,Undo2,Redo2,Settings2,Play,Pause,Trash2,Copy,X,PaintBucket,Unlink,Film} from 'lucide-react';
import {resolveShapes,interpolateShapes,interpolateScene,drawShape,initialFrames,GRID_SIZE,worldToLocal,localToWorld,lineGeometry,fromLinePoints} from '../lib/animation';
import {snapEndpoint,alignCamera,drawGrid,startingGridScale} from '../lib/view';
import MovieExport from './movie-export';
import TouchPreview from './touch-preview';
import Voiceover from './voiceover';
import MovieSave from './movie-save';
import CameraOverlay,{useFrontCamera} from './camera-overlay';
import FrameTimeline from './frame-timeline';
import {boxSelection,selectionBounds,moveSelection,duplicateSelection,reorderFrames,deleteFrame,styleSelection} from '../lib/editing';
import {DEFAULT_STYLE,DEFAULT_EASING,newShapeStyle} from '../lib/defaults';
import {MOVIE_FPS} from '../lib/movie';
const uid=()=>Math.random().toString(36).slice(2,10);
const toolList=[['select',MousePointer2,'Select','V'],['line',Minus,'Line','L'],['circle',Circle,'Circle','O'],['rect',Square,'Square','R']];
function IconButton({icon:Icon,label,active,className='',...props}){return <button type="button" className={`icon-button ${active?'active':''} ${className}`} title={label} aria-label={label} aria-pressed={active===undefined?undefined:active} {...props}><Icon size={20} strokeWidth={1.65}/></button>}
export default function Editor(){
 const[frames,setFrames]=useState(()=>structuredClone(initialFrames)),[frame,setFrame]=useState(0),[selected,setSelected]=useState([]),[tool,setTool]=useState('select');
 const[snap,setSnap]=useState(true),[grid,setGrid]=useState(true),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[duration,setDuration]=useState(1),[loop,setLoop]=useState(true),[easing,setEasing]=useState(DEFAULT_EASING),[settings,setSettings]=useState(false),[snapHint,setSnapHint]=useState(null),[touchPreview,setTouchPreview]=useState(null),[exportOpen,setExportOpen]=useState(false),[movieFps,setMovieFps]=useState(30),[voiceMode,setVoiceMode]=useState(false),[voicePaused,setVoicePaused]=useState(false),[recordedMovie,setRecordedMovie]=useState(null);
 const[drawingStyle,setDrawingStyle]=useState(DEFAULT_STYLE),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[size,setSize]=useState({w:1000,h:650});
 const[marquee,setMarquee]=useState(null),[manipulating,setManipulating]=useState(false);
 const camera=useFrontCamera(size);
 const canvasRef=useRef(null),stageRef=useRef(null),gesture=useRef(null),pointers=useRef(new Map()),framesRef=useRef(frames),settingsRef=useRef(null),settingsButtonRef=useRef(null),viewRef=useRef(null),wheelTimer=useRef(null),voiceTween=useRef(null),voiceScene=useRef([]),renderScene=useRef(null),voiceModeRef=useRef(false),recordingView=useRef(null);
 framesRef.current=frames;const shapes=resolveShapes(frames,frame),selectedShapes=shapes.filter(s=>selected.includes(s.id)),shape=selectedShapes.length===1?selectedShapes[0]:null,bounds=selectionBounds(selectedShapes);const baseScale=startingGridScale(size.w),scale=baseScale*zoom;const origin={x:pan.x,y:pan.y};
 recordingView.current={width:size.w,height:size.h,scale,origin};
 const getRecordingScene=useCallback(()=>({view:recordingView.current,shapes:voiceScene.current,includeGrid:viewRef.current.grid}),[]);
 viewRef.current={size,baseScale,zoom,pan,scale,origin,snap,grid};voiceModeRef.current=voiceMode;
 const remember=()=>{setHistory(h=>[...h.slice(-49),JSON.stringify({frames:framesRef.current,frame})]);setFuture([])};
 function patchMany(changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:Object.fromEntries([...new Set([...Object.keys(f.changes),...Object.keys(changes)])].map(id=>[id,{...f.changes[id],...changes[id]}]))}:f))}
 function patch(id,changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:{...f.changes,[id]:{...f.changes[id],...changes}}}:f))}
 function undo(){if(!history.length)return;const prev=JSON.parse(history.at(-1));setFuture(f=>[...f,JSON.stringify({frames,frame})]);setHistory(h=>h.slice(0,-1));setFrames(prev.frames);setFrame(prev.frame);setSelected([]);setPlaying(false)}
 function redo(){if(!future.length)return;const next=JSON.parse(future.at(-1));setHistory(h=>[...h,JSON.stringify({frames,frame})]);setFuture(f=>f.slice(0,-1));setFrames(next.frames);setFrame(next.frame);setSelected([]);setPlaying(false)}
 function chooseFrame(i){setPlaying(false);setFrame(i);setPosition(i);setSnapHint(null);setSelected([])}
 function addFrame(){remember();const next=[...frames];next.splice(frame+1,0,{id:uid(),changes:{}});setFrames(next);chooseFrame(frame+1)}
 function removeFrame(index=frame){if(frames.length<2)return;remember();setFrames(deleteFrame(frames,index));chooseFrame(Math.max(0,index-1));setSelected([])}
 function copyFrame(index){remember();const next=[...frames];next.splice(index+1,0,{id:uid(),changes:structuredClone(frames[index].changes)});setFrames(next);chooseFrame(index+1);setSelected([])}
 function reorderFrame(from,to){if(from===to)return;remember();setFrames(reorderFrames(frames,from,to));chooseFrame(to);setSelected([])}
 function deleteShape(){if(selectedShapes.length){patchMany(Object.fromEntries(selectedShapes.map(s=>[s.id,{visible:false}])));setSelected([])}}
 function duplicateShape(){if(!selectedShapes.length)return;const copies=duplicateSelection(selectedShapes,uid,GRID_SIZE);patchMany(Object.fromEntries(copies.map(s=>[s.id,s])));setSelected(copies.map(s=>s.id))}
 function unlink(){patchMany(Object.fromEntries(selectedShapes.filter(s=>s.type==='line').map(s=>[s.id,{...fromLinePoints(...Object.values(lineGeometry(s))),startLink:null,endLink:null}])))}
 function togglePlay(){if(playing){setPlaying(false);setFrame(Math.min(frames.length-1,Math.round(position)));return}if(frames.length<2)return;setPosition(!loop&&frame===frames.length-1?0:frame);setSelected([]);setPlaying(true)}
 function enterVoice(){setPlaying(false);setSelected([]);setTouchPreview(null);setSnapHint(null);setPosition(frame);voiceScene.current=resolveShapes(frames,frame);voiceTween.current=null;setVoicePaused(false);setVoiceMode(true)}
 function voiceFrame(target){voiceTween.current={from:voiceScene.current,to:resolveShapes(framesRef.current,target),elapsed:0};setFrame(target)}
 function finishVoice(movie){camera.close();voiceTween.current=null;setVoiceMode(false);setVoicePaused(false);setPosition(frame);if(movie)setRecordedMovie(movie)}
 useEffect(()=>{if(!voiceMode||voicePaused)return;let raf,last=performance.now();const tick=now=>{const tween=voiceTween.current;if(tween){tween.elapsed+=now-last;const t=Math.min(1,tween.elapsed/(duration*1000));voiceScene.current=interpolateScene(tween.from,tween.to,t,easing);renderScene.current?.();if(t===1)voiceTween.current=null}last=now;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[voiceMode,voicePaused,duration,easing]);
 useEffect(()=>{const ro=new ResizeObserver(([entry])=>setSize({w:entry.contentRect.width,h:entry.contentRect.height,orientation:window.innerWidth>=window.innerHeight?'landscape':'portrait'}));ro.observe(stageRef.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{
  const canvas=canvasRef.current;
  const wheel=e=>{e.preventDefault();if(voiceModeRef.current)return;const v=viewRef.current,r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;
   const nextZoom=Math.max(.4,Math.min(4,v.zoom*Math.exp(-e.deltaY*.002))),nextScale=v.baseScale*nextZoom;
   const world={x:(x-v.origin.x)/v.scale,y:(y-v.origin.y)/v.scale};
   const nextPan={x:x-world.x*nextScale,y:y-world.y*nextScale};
   setZoom(nextZoom);setPan(nextPan);viewRef.current={...v,zoom:nextZoom,pan:nextPan,scale:nextScale,origin:{...nextPan}};
   clearTimeout(wheelTimer.current);wheelTimer.current=setTimeout(()=>{const latest=viewRef.current;if(latest.snap){const aligned=alignCamera(latest.size,latest.baseScale,latest.zoom,latest.pan);setZoom(aligned.zoom);setPan(aligned.pan)}},160);
  };
  canvas.addEventListener('wheel',wheel,{passive:false});return()=>{canvas.removeEventListener('wheel',wheel);clearTimeout(wheelTimer.current)};
 },[]);

 useEffect(()=>{if(!playing)return;let raf,last=performance.now(),p=position;const tick=now=>{p+=(now-last)/(duration*1000);last=now;if(p>=(loop?frames.length:frames.length-1)){if(loop&&frames.length>1)p%=frames.length;else{setPlaying(false);setFrame(frames.length-1);setPosition(frames.length-1);return}}setPosition(p);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing,duration,loop,frames.length]);
 useEffect(()=>{const key=e=>{if(e.target.closest('input,select,textarea,.camera-window,.mini-menu,.frame-card')||settings||exportOpen||voiceMode||recordedMovie)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&e.key==='d'){e.preventDefault();duplicateShape();return}if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteShape()}else if(e.key==='Escape'){setSelected([]);setPlaying(false)}else if(e.key==='ArrowRight')chooseFrame(Math.min(frames.length-1,frame+1));else if(e.key==='ArrowLeft')chooseFrame(Math.max(0,frame-1));else if(e.key.toLowerCase()==='n')addFrame();else{const t=toolList.find(t=>t[3].toLowerCase()===e.key.toLowerCase());if(t){setPlaying(false);setTool(t[0])}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 useEffect(()=>{if(!settings)return;settingsRef.current?.querySelector('button')?.focus();const onKey=e=>{if(e.key==='Escape')setSettings(false);if(e.key==='Tab'){const els=[...settingsRef.current.querySelectorAll('button:not(:disabled),input,select')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('keydown',onKey);settingsButtonRef.current?.focus()}},[settings]);
 const toWorld=p=>{const r=canvasRef.current.getBoundingClientRect();return{x:(p.clientX-r.left-origin.x)/scale,y:(p.clientY-r.top-origin.y)/scale}};
 const snapped=p=>snap?{x:Math.round(p.x/GRID_SIZE)*GRID_SIZE,y:Math.round(p.y/GRID_SIZE)*GRID_SIZE}:p;
 function endpoint(p,id){const result=snapEndpoint(resolveShapes(framesRef.current,frame),p,id,scale,snap);setSnapHint(snap?result.point:null);return result}
 function showTouch(e,p){if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const r=canvasRef.current.getBoundingClientRect();setTouchPreview({x:e.clientX-r.left,y:e.clientY-r.top,world:p})}
 function hit(p,s){const q=worldToLocal(s,p),pad=14/scale;if(s.type==='circle')return((q.x-s.w/2)/(Math.abs(s.w/2)+pad))**2+((q.y-s.h/2)/(Math.abs(s.h/2)+pad))**2<=1;if(s.type==='rect')return q.x>=-pad&&q.y>=-pad&&q.x<=s.w+pad&&q.y<=s.h+pad;for(let t=0;t<=1;t+=.015){const x=2*(1-t)*t*s.cx+t*t*s.w,y=2*(1-t)*t*s.cy+t*t*s.h;if(Math.hypot(q.x-x,q.y-y)<pad+s.stroke)return true}return false}
 function pointerDown(e){if(voiceMode||e.button>1)return;setManipulating(true);e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pointers.current.size===2){const ps=[...pointers.current.values()],g=gesture.current;if(g?.beforeFrames){setFrames(g.beforeFrames);setHistory(h=>h.slice(0,g.historyLength))}const center={clientX:(ps[0].clientX+ps[1].clientX)/2,clientY:(ps[0].clientY+ps[1].clientY)/2};gesture.current={type:'pinch',distance:Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),zoom,world:toWorld(center)};setSnapHint(null);setTouchPreview(null);setMarquee(null);if(g?.selected)setSelected(g.selected);return}if(playing||pointers.current.size>1)return;
 const p=toWorld(e),baseline={beforeFrames:frames,historyLength:history.length,selected:[...selected]};if(e.button===1){gesture.current={type:'pan',start:{x:e.clientX,y:e.clientY},pan};return}
 if(shape&&tool==='select'&&!e.shiftKey){const q=worldToLocal(shape,p),handles=shape.type==='line'?[{x:0,y:0,key:'start'},{x:shape.w,y:shape.h,key:'end'},{x:shape.cx,y:shape.cy,key:'control'}]:[{x:0,y:0,key:'scale-tl'},{x:shape.w,y:0,key:'scale-tr'},{x:0,y:shape.h,key:'scale-bl'},{x:shape.w,y:shape.h,key:'scale-br'}];const h=handles.find(h=>Math.hypot(q.x-h.x,q.y-h.y)<20/scale);if(h){if(shape.type==='line')showTouch(e,p);remember();gesture.current={...baseline,type:h.key,start:p,shape:{...shape}};return}}
 if(tool==='select'){
  const target=[...shapes].reverse().find(s=>hit(p,s));
  if(target){
   const ids=e.shiftKey?(selected.includes(target.id)?selected.filter(id=>id!==target.id):[...selected,target.id]):selected.includes(target.id)?selected:[target.id];
   setSelected(ids);if(ids.length===1){const brush=shapes.find(s=>s.id===ids[0]);setDrawingStyle({color:brush.color,strokeColor:brush.strokeColor||brush.color,stroke:brush.stroke})}if(ids.includes(target.id)){gesture.current={...baseline,type:'move',start:p,shape:{...target},shapes:shapes.filter(s=>ids.includes(s.id)),moved:false}}return;
  }
  const base=e.shiftKey?selected:[];setSelected(base);setMarquee({start:p,end:p});gesture.current={type:'box',start:p,base,selected:[...selected]};return;
 }

 const id=uid(),connection=tool==='line'?endpoint(p,id):{point:snapped(p),link:null},start=connection.point,s={id,type:tool,name:tool==='rect'?'Square':tool==='circle'?'Circle':'Line',x:start.x,y:start.y,w:0,h:0,cx:0,cy:0,...newShapeStyle(tool,drawingStyle),opacity:1,rotation:0,visible:true,startLink:connection.link,endLink:null};if(tool==='line')showTouch(e,p);remember();patch(id,s,false);setSelected([id]);gesture.current={...baseline,type:'draw',start,shape:s};
 }
 function pointerMove(e){if(pointers.current.has(e.pointerId))pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});const g=gesture.current;if(!g)return;if(g.type==='pinch'){const ps=[...pointers.current.values()];if(ps.length!==2)return;const distance=Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),nextZoom=Math.max(.4,Math.min(4,g.zoom*distance/Math.max(1,g.distance))),nextScale=baseScale*nextZoom,r=canvasRef.current.getBoundingClientRect(),center={x:(ps[0].clientX+ps[1].clientX)/2-r.left,y:(ps[0].clientY+ps[1].clientY)/2-r.top};const nextPan={x:center.x-g.world.x*nextScale,y:center.y-g.world.y*nextScale};g.camera={zoom:nextZoom,pan:nextPan};setZoom(nextZoom);setPan(nextPan);return}if(g.type==='pan'){setPan({x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y});return}
 const raw=toWorld(e),p=snapped(raw),s=g.shape,dx=raw.x-g.start.x,dy=raw.y-g.start.y;
 if(g.type==='box'){setMarquee({start:g.start,end:raw});setSelected([...new Set([...g.base,...boxSelection(shapes,g.start,raw)])]);return}
 if(s.type==='line')showTouch(e,raw);
 if(g.type==='move'){if(!g.moved&&Math.hypot(dx,dy)*scale<4)return;if(!g.moved){remember();g.moved=true}const point=snapped({x:s.x+dx,y:s.y+dy});patchMany(moveSelection(g.shapes,point.x-s.x,point.y-s.y),false);return}
 if(g.type==='draw'){if(s.type==='line'){const target=endpoint(raw,s.id),end=target.point;patch(s.id,{...fromLinePoints(g.start,end,{x:(g.start.x+end.x)/2,y:(g.start.y+end.y)/2}),endLink:target.link},false)}else{let w=p.x-g.start.x,h=p.y-g.start.y;if(e.shiftKey){const a=Math.max(Math.abs(w),Math.abs(h));w=Math.sign(w||1)*a;h=Math.sign(h||1)*a}patch(s.id,{x:Math.min(g.start.x,g.start.x+w),y:Math.min(g.start.y,g.start.y+h),w:Math.abs(w),h:Math.abs(h)},false)}}
 if(g.type==='control'){setSnapHint(snap?p:null);const points=lineGeometry(s);patch(s.id,fromLinePoints(points.start,points.end,p),false)}
 if(g.type==='start'||g.type==='end'){const target=endpoint(raw,s.id),points=lineGeometry(s);points[g.type]=target.point;patch(s.id,{...fromLinePoints(points.start,points.end,points.control),[g.type==='start'?'startLink':'endLink']:target.link},false)}
 if(g.type.startsWith('scale-')){const q=worldToLocal(s,p),corner=g.type.slice(6);let left=0,top=0,right=s.w,bottom=s.h;if(corner[1]==='l')left=Math.min(q.x,s.w-20);else right=Math.max(20,q.x);if(corner[0]==='t')top=Math.min(q.y,s.h-20);else bottom=Math.max(20,q.y);if(e.shiftKey){const height=(right-left)*s.h/s.w;if(corner[0]==='t')top=bottom-height;else bottom=top+height}const w=right-left,h=bottom-top,center=localToWorld(s,{x:(left+right)/2,y:(top+bottom)/2});patch(s.id,{x:center.x-w/2,y:center.y-h/2,w,h},false)}
 }
 function pointerUp(e){pointers.current.delete(e.pointerId);setManipulating(false);setMarquee(null);const g=gesture.current;if(g?.type==='pinch'&&snap){const camera=g.camera||{zoom,pan};const aligned=alignCamera(size,baseScale,camera.zoom,camera.pan);setZoom(aligned.zoom);setPan(aligned.pan)}if(g?.type==='draw'){const s=resolveShapes(framesRef.current,frame).find(s=>s.id===g.shape.id);if(s&&Math.abs(s.w)+Math.abs(s.h)<4)patch(s.id,{w:160,h:s.type==='line'?0:160,cx:80,cy:s.type==='line'?0:80,endLink:null},false);setTool('select')}gesture.current=null;setSnapHint(null);setTouchPreview(null)}
 useEffect(()=>{const draw=()=>{const canvas=canvasRef.current,ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(size.w*dpr)||canvas.height!==Math.round(size.h*dpr)){canvas.width=Math.round(size.w*dpr);canvas.height=Math.round(size.h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size.w,size.h);
 if(grid)drawGrid(ctx,size.w,size.h,scale,origin);
 ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(scale,scale);const rendered=voiceMode?voiceScene.current:playing?interpolateShapes(frames,position,easing,loop):shapes;rendered.forEach(s=>drawShape(ctx,s));
 if(!playing&&!voiceMode)for(const s of selectedShapes){ctx.save();ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-s.w/2,-s.h/2);ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;const handles=[];
 if(s.type==='line'){ctx.setLineDash([4/scale,4/scale]);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(s.cx,s.cy);ctx.lineTo(s.w,s.h);ctx.stroke();ctx.setLineDash([]);handles.push([0,0,!!s.startLink],[s.w,s.h,!!s.endLink],[s.cx,s.cy,false])}else{ctx.strokeRect(0,0,s.w,s.h);handles.push([0,0],[s.w,0],[0,s.h],[s.w,s.h])}
 (selectedShapes.length===1?handles:[]).forEach(([x,y,linked])=>{ctx.fillStyle=linked?'#b4d7a0':'#202229';ctx.strokeStyle=linked?'#b4d7a0':'#c6b2ff';ctx.lineWidth=1.5/scale;ctx.beginPath();ctx.arc(x,y,(linked?5:4)/scale,0,Math.PI*2);ctx.fill();ctx.stroke();if(linked){ctx.beginPath();ctx.arc(x,y,8/scale,0,Math.PI*2);ctx.stroke()}});ctx.restore()}
 if(bounds&&selectedShapes.length>1&&!playing&&!voiceMode){ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;ctx.setLineDash([5/scale,4/scale]);ctx.strokeRect(bounds.left-8/scale,bounds.top-8/scale,bounds.right-bounds.left+16/scale,bounds.bottom-bounds.top+16/scale);ctx.setLineDash([])}
 if(snapHint){ctx.strokeStyle='#b4d7a0';ctx.lineWidth=2/scale;ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,11/scale,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b4d7a0';ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,3/scale,0,Math.PI*2);ctx.fill()}ctx.restore();
 };renderScene.current=draw;draw();return()=>{renderScene.current=null}},[frames,frame,selected,position,playing,size,zoom,pan,grid,easing,loop,snapHint,voiceMode]);
 const menuWidth=Math.min(selectedShapes.some(s=>s.startLink||s.endLink)?364:316,size.w-16),menuX=bounds?Math.max(8,Math.min(size.w-menuWidth-8,origin.x+(bounds.left+bounds.right)*scale/2-menuWidth/2)):8;
 const above=bounds?origin.y+bounds.top*scale-62:8,menuY=Math.max(8,Math.min(size.h-60,above>=8?above:origin.y+(bounds?.bottom||0)*scale+16));
 return <main className="editor"><section className="stage" ref={stageRef}><canvas className={`main-canvas tool-${tool}`} ref={canvasRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} aria-label="Animation drawing canvas"/>{touchPreview&&<TouchPreview touch={touchPreview} size={size} scale={scale} shapes={shapes} selected={shape?.id} grid={grid} hint={snapHint}/>}{marquee&&<div className="selection-box" style={{left:origin.x+Math.min(marquee.start.x,marquee.end.x)*scale,top:origin.y+Math.min(marquee.start.y,marquee.end.y)*scale,width:Math.abs(marquee.end.x-marquee.start.x)*scale,height:Math.abs(marquee.end.y-marquee.start.y)*scale}}/>}
 {selectedShapes.length>0&&!playing&&!voiceMode&&!manipulating&&!settings&&!exportOpen&&!recordedMovie&&<div className="mini-menu shape-menu" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();setSelected([])}}} role="toolbar" aria-label={selectedShapes.length===1?'Shape actions':`${selectedShapes.length} selected shapes`} style={{left:menuX,top:menuY,maxWidth:menuWidth}}>
 <label className="menu-color" title="Fill color"><span style={{background:selectedShapes[0].color}}/><input type="color" aria-label="Fill color" value={selectedShapes[0].color} onChange={e=>{setDrawingStyle(s=>({...s,color:e.target.value}));patchMany(styleSelection(selectedShapes,'color',e.target.value))}}/></label>
 <label className="menu-color stroke-color" title="Stroke color"><span style={{borderColor:selectedShapes[0].strokeColor||selectedShapes[0].color}}/><input type="color" aria-label="Stroke color" value={selectedShapes[0].strokeColor||selectedShapes[0].color} onChange={e=>{setDrawingStyle(s=>({...s,strokeColor:e.target.value}));patchMany(styleSelection(selectedShapes,'strokeColor',e.target.value))}}/></label>
 <label className="stroke-width" title="Stroke width"><span>Stroke</span><input aria-label="Stroke width" type="number" inputMode="decimal" min="0" max="80" step="1" value={selectedShapes[0].stroke} onChange={e=>{setDrawingStyle(s=>({...s,stroke:Math.max(0,Math.min(80,Number(e.target.value)||0))}));patchMany(styleSelection(selectedShapes,'stroke',e.target.value))}}/></label>
 <IconButton icon={PaintBucket} label="Toggle fill" disabled={selectedShapes.every(s=>s.type==='line')} active={selectedShapes.every(s=>s.fill)} onClick={()=>patchMany(Object.fromEntries(selectedShapes.filter(s=>s.type!=='line').map(s=>[s.id,{fill:!selectedShapes.every(s=>s.type==='line'||s.fill)}])))}/>
 <IconButton icon={Copy} label="Duplicate selected shapes" onClick={duplicateShape}/><IconButton icon={Trash2} label="Delete selected shapes" onClick={deleteShape}/>{selectedShapes.some(s=>s.startLink||s.endLink)&&<IconButton icon={Unlink} label="Disconnect selected lines" onClick={unlink}/>}</div>}
 <CameraOverlay camera={camera} size={size}/></section>
 <div className="controls">{voiceMode?<Voiceover getRecordingScene={getRecordingScene} camera={camera} canvasRef={canvasRef} fps={movieFps} orientation={size.orientation} onPaused={setVoicePaused} onDone={finishVoice} onExport={()=>setExportOpen(true)}/>:<div className="tool-row"><div className="undo-tools" aria-label="History and playback"><IconButton icon={Undo2} label="Undo (⌘Z)" disabled={!history.length} onClick={undo}/><IconButton icon={Redo2} label="Redo (⌘⇧Z)" disabled={!future.length} onClick={redo}/><IconButton icon={playing?Pause:Play} label={playing?'Pause (Space)':'Play (Space)'} className="play-button" disabled={frames.length<2} onClick={togglePlay}/></div><nav className="tool-scroll" aria-label="Drawing tools and settings">{toolList.map(([id,Icon,label,key])=><span className="tool-pair" key={id}><IconButton icon={Icon} label={`${label} (${key})`} active={tool===id} onClick={()=>{setPlaying(false);setTool(id)}}/>{id==='select'&&<IconButton icon={Magnet} label="Snap to grid and shapes" active={snap} onClick={()=>setSnap(!snap)}/>}</span>)}<span className="separator"/><IconButton icon={Film} label="Recording area" onClick={enterVoice}/><button ref={settingsButtonRef} className="icon-button" aria-label="Settings" title="Settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></nav></div>}
 <FrameTimeline frames={frames} frame={frame} playing={playing} position={position} recording={voiceMode} onChoose={voiceMode?voiceFrame:chooseFrame} onAdd={addFrame} onCopy={copyFrame} onDelete={removeFrame} onReorder={reorderFrame}/></div>
 {exportOpen&&<MovieExport getCameraOverlay={camera.getOverlay} frames={frames} duration={duration} loop={loop} easing={easing} fps={movieFps} onFpsChange={setMovieFps} view={{width:size.w,height:size.h,orientation:size.orientation,scale,origin}} onClose={()=>setExportOpen(false)}/>}
 {recordedMovie&&<MovieSave recording={recordedMovie} onClose={()=>setRecordedMovie(null)}/>}
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><div ref={settingsRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><div className="modal-heading"><h2 id="settings-title">Settings</h2><IconButton icon={X} label="Close settings" onClick={()=>setSettings(false)}/></div><label className="settings-row"><span>Seconds between frames</span><input type="number" inputMode="decimal" min="0.1" max="30" step="0.1" value={duration} onChange={e=>setDuration(Math.max(.1,Math.min(30,+e.target.value||1)))}/></label><label className="settings-row"><span>Movie frame rate</span><select value={movieFps} onChange={e=>setMovieFps(Number(e.target.value))}>{MOVIE_FPS.map(fps=><option key={fps} value={fps}>{fps} fps</option>)}</select></label><label className="settings-row"><span>Transition</span><select value={easing} onChange={e=>setEasing(e.target.value)}><option value="smooth">Smooth</option><option value="linear">Linear</option></select></label><label className="settings-row"><span>Loop playback</span><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/></label><label className="settings-row"><span>Show grid</span><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/></label><label className="settings-row"><span>Snap to grid and shapes</span><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/></label><button className="done-button" onClick={()=>setSettings(false)}>Done</button></div></div>}
 </main>
}
