'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {MousePointer2,Minus,Circle,Square,Magnet,Undo2,Redo2,Settings2,Play,Pause,Trash2,Copy,X,PaintBucket,Unlink,Film,ClipboardPaste,Focus,Group,LogOut,LogIn} from 'lucide-react';
import {resolveShapes,interpolateShapes,interpolateScene,drawShape,initialFrames,worldToLocal,localToWorld,lineGeometry,fromLinePoints,symbolCycleDuration} from '../lib/animation';
import {snapEndpoint,alignCamera,drawGrid,startingGridScale,gridLevel,gridSpacing,MAX_ZOOM} from '../lib/view';
import MovieExport from './movie-export';
import TouchPreview from './touch-preview';
import Voiceover from './voiceover';
import MovieSave from './movie-save';
import CameraOverlay,{useFrontCamera} from './camera-overlay';
import FrameTimeline from './frame-timeline';
import {boxSelectParts,mergePoints,moveParts,partsBounds,reorderFrames,deleteFrame,styleSelection} from '../lib/editing';
import {DEFAULT_STYLE,DEFAULT_EASING,newShapeStyle} from '../lib/defaults';
import {timelineOf,updateTimeline,groupIntoSymbol,copyShapes,pasteShapes} from '../lib/symbols';
import {MOVIE_FPS} from '../lib/movie';
const uid=()=>Math.random().toString(36).slice(2,10);
const toolList=[['select',MousePointer2,'Select','V'],['line',Minus,'Line','L'],['circle',Circle,'Circle','O'],['rect',Square,'Square','R']];
function IconButton({icon:Icon,label,active,className='',...props}){return <button type="button" className={`icon-button ${active?'active':''} ${className}`} title={label} aria-label={label} aria-pressed={active===undefined?undefined:active} {...props}><Icon size={20} strokeWidth={1.65}/></button>}
export default function Editor(){
 const[project,setProject]=useState(()=>({frames:structuredClone(initialFrames),symbols:{},duration:1,easing:DEFAULT_EASING})),[scope,setScope]=useState(null),[path,setPath]=useState([]);
 const timeline=timelineOf(project,scope),{frames,duration,easing}=timeline;
 const setFrames=next=>setProject(p=>updateTimeline(p,scope,{frames:typeof next==='function'?next(timelineOf(p,scope).frames):next}));
 const setDuration=value=>{remember();setProject(p=>updateTimeline(p,scope,{duration:value}))},setEasing=value=>{remember();setProject(p=>updateTimeline(p,scope,{easing:value}))};
 const[frame,setFrame]=useState(0),[selected,setSelected]=useState([]),[selectedPoints,setSelectedPoints]=useState({}),[tool,setTool]=useState('select'),[clipboard,setClipboard]=useState(null);
 const[snap,setSnap]=useState(true),[grid,setGrid]=useState(true),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[sceneTime,setSceneTime]=useState(0),[loop,setLoop]=useState(true),[settings,setSettings]=useState(false),[snapHint,setSnapHint]=useState(null),[touchPreview,setTouchPreview]=useState(null),[exportOpen,setExportOpen]=useState(false),[movieFps,setMovieFps]=useState(30),[voiceMode,setVoiceMode]=useState(false),[voicePaused,setVoicePaused]=useState(false),[recordedMovie,setRecordedMovie]=useState(null);
 const[drawingStyle,setDrawingStyle]=useState(DEFAULT_STYLE),[history,setHistory]=useState([]),[future,setFuture]=useState([]),[size,setSize]=useState({w:1000,h:650});
 const[marquee,setMarquee]=useState(null),[manipulating,setManipulating]=useState(false);
 const camera=useFrontCamera(size);
 const canvasRef=useRef(null),stageRef=useRef(null),gesture=useRef(null),pointers=useRef(new Map()),framesRef=useRef(frames),projectRef=useRef(project),settingsRef=useRef(null),settingsButtonRef=useRef(null),viewRef=useRef(null),wheelTimer=useRef(null),voiceTween=useRef(null),voiceScene=useRef([]),voiceTime=useRef(0),renderScene=useRef(null),voiceModeRef=useRef(false),recordingView=useRef(null),lastTap=useRef(null);
 framesRef.current=frames;projectRef.current=project;
 const shapes=resolveShapes(frames,frame),selectedShapes=shapes.filter(s=>selected.includes(s.id)||selectedPoints[s.id]?.length),shape=selected.length===1&&!Object.keys(selectedPoints).length?selectedShapes[0]:null,bounds=partsBounds(shapes,selected,selectedPoints);
 const baseScale=startingGridScale(size.w),scale=baseScale*zoom,level=gridLevel(zoom),spacing=gridSpacing(zoom),origin={x:pan.x,y:pan.y},canPlay=frames.length>1||symbolCycleDuration(shapes,project.symbols)>0;
 recordingView.current={width:size.w,height:size.h,scale,origin,gridLevel:level};
 const getRecordingScene=useCallback(()=>({view:recordingView.current,shapes:voiceScene.current,includeGrid:viewRef.current.grid,symbols:projectRef.current.symbols,time:voiceTime.current}),[]);
 viewRef.current={size,baseScale,zoom,pan,scale,origin,snap,grid};voiceModeRef.current=voiceMode;
 const snapshot=()=>JSON.stringify({project:projectRef.current,scope,path,frame,zoom,pan});
 const remember=()=>{setHistory(h=>[...h.slice(-49),snapshot()]);setFuture([])};
 function clearSelection(){setSelected([]);setSelectedPoints({})}
 function restore(value){const state=JSON.parse(value);setProject(state.project);setScope(state.scope);setPath(state.path);setFrame(state.frame);setPosition(state.frame);setSceneTime(state.frame*timelineOf(state.project,state.scope).duration);setZoom(state.zoom);setPan(state.pan);clearSelection();setPlaying(false);setTouchPreview(null)}
 function resetCamera(){clearTimeout(wheelTimer.current);setZoom(1);setPan({x:0,y:0});setTouchPreview(null);setSnapHint(null)}
 function patchMany(changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:Object.fromEntries([...new Set([...Object.keys(f.changes),...Object.keys(changes)])].map(id=>[id,{...f.changes[id],...changes[id]}]))}:f))}
 function patch(id,changes,record=true){if(record)remember();setFrames(fs=>fs.map((f,i)=>i===frame?{...f,changes:{...f.changes,[id]:{...f.changes[id],...changes}}}:f))}
 function undo(){if(!history.length)return;setFuture(f=>[...f,snapshot()]);setHistory(h=>h.slice(0,-1));restore(history.at(-1))}
 function redo(){if(!future.length)return;setHistory(h=>[...h,snapshot()]);setFuture(f=>f.slice(0,-1));restore(future.at(-1))}
 function chooseFrame(i){setPlaying(false);setFrame(i);setPosition(i);setSceneTime(i*duration);setSnapHint(null);clearSelection()}
 function addFrame(){remember();const next=[...frames];next.splice(frame+1,0,{id:uid(),changes:{}});setFrames(next);chooseFrame(frame+1)}
 function removeFrame(index=frame){if(frames.length<2)return;remember();setFrames(deleteFrame(frames,index));chooseFrame(Math.max(0,index-1));setSelected([])}
 function copyFrame(index){remember();const next=[...frames];next.splice(index+1,0,{id:uid(),changes:structuredClone(frames[index].changes)});setFrames(next);chooseFrame(index+1);setSelected([])}
 function reorderFrame(from,to){if(from===to)return;remember();setFrames(reorderFrames(frames,from,to));chooseFrame(to);setSelected([])}
 function deleteShape(){if(selectedShapes.length){patchMany(Object.fromEntries(selectedShapes.map(s=>[s.id,{visible:false}])));clearSelection()}}
 function copySelection(){if(selectedShapes.length)setClipboard({...copyShapes(selectedShapes,project.symbols),sourceScope:scope,sourceFrame:frames[frame].id})}
 function pasteSelection(){if(!clipboard)return;const copies=pasteShapes(clipboard,uid,clipboard.sourceScope===scope&&clipboard.sourceFrame===frames[frame].id?spacing:0,frame*duration);remember();setProject(p=>{const fs=timelineOf(p,scope).frames.map((f,i)=>i===frame?{...f,changes:{...f.changes,...Object.fromEntries(copies.shapes.map(s=>[s.id,s]))}}:f);return updateTimeline({...p,symbols:{...p.symbols,...copies.symbols}},scope,{frames:fs})});setSelected(copies.shapes.map(s=>s.id));setSelectedPoints({});setTool('select')}
 function makeSymbol(){const grouped=groupIntoSymbol(frames,frame,selectedShapes.map(s=>s.id),uid,duration,easing);if(!grouped)return;remember();setProject(p=>updateTimeline({...p,symbols:{...p.symbols,[grouped.definition.id]:grouped.definition}},scope,{frames:grouped.frames}));setSelected([grouped.instance.id]);setSelectedPoints({});setTool('select')}
 function enterSymbol(instance){if(!project.symbols[instance.symbolId])return;setPath(p=>[...p,{scope,frame,zoom,pan}]);setScope(instance.symbolId);setFrame(0);setPosition(0);setSceneTime(0);setPlaying(false);clearSelection();resetCamera();lastTap.current=null}
 function exitSymbol(){const parent=path.at(-1);if(!parent)return;setPath(p=>p.slice(0,-1));setScope(parent.scope);setFrame(parent.frame);setPosition(parent.frame);setSceneTime(parent.frame*timelineOf(project,parent.scope).duration);setZoom(parent.zoom);setPan(parent.pan);setPlaying(false);clearSelection()}
 function toggleFill(){const fill=!selectedShapes.every(s=>s.type==='line'||s.fill);setDrawingStyle(s=>({...s,fill}));patchMany(Object.fromEntries(selectedShapes.filter(s=>s.type!=='line').map(s=>[s.id,{fill}])))}
 function unlink(){patchMany(Object.fromEntries(selectedShapes.filter(s=>s.type==='line').map(s=>[s.id,{...fromLinePoints(...Object.values(lineGeometry(s))),startLink:null,endLink:null}])))}
 function togglePlay(){if(playing){setPlaying(false);setFrame(Math.min(frames.length-1,Math.round(position)));return}if(!canPlay)return;const start=!loop&&frame===frames.length-1?0:frame;setPosition(start);setSceneTime(start*duration);clearSelection();setPlaying(true)}
 function enterVoice(){setPlaying(false);clearSelection();voiceTime.current=frame*duration;setTouchPreview(null);setSnapHint(null);setPosition(frame);voiceScene.current=resolveShapes(frames,frame);voiceTween.current=null;setVoicePaused(false);setVoiceMode(true)}
 function voiceFrame(target){voiceTween.current={from:voiceScene.current,to:resolveShapes(framesRef.current,target),elapsed:0};setFrame(target)}
 function finishVoice(movie){camera.close();voiceTween.current=null;setVoiceMode(false);setVoicePaused(false);setPosition(frame);setSceneTime(voiceTime.current);if(movie)setRecordedMovie(movie)}
 useEffect(()=>{if(!voiceMode||voicePaused)return;let raf,last=performance.now();const tick=now=>{voiceTime.current+=(now-last)/1000;const tween=voiceTween.current;if(tween){tween.elapsed+=now-last;const t=Math.min(1,tween.elapsed/(duration*1000));voiceScene.current=interpolateScene(tween.from,tween.to,t,easing);if(t===1)voiceTween.current=null}renderScene.current?.();last=now;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[voiceMode,voicePaused,duration,easing]);
 useEffect(()=>{const ro=new ResizeObserver(([entry])=>setSize({w:entry.contentRect.width,h:entry.contentRect.height,orientation:window.innerWidth>=window.innerHeight?'landscape':'portrait'}));ro.observe(stageRef.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{
  const canvas=canvasRef.current;
  const wheel=e=>{e.preventDefault();if(voiceModeRef.current)return;const v=viewRef.current,r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;
   const nextZoom=Math.max(.4,Math.min(MAX_ZOOM,v.zoom*Math.exp(-e.deltaY*.002))),nextScale=v.baseScale*nextZoom;
   const world={x:(x-v.origin.x)/v.scale,y:(y-v.origin.y)/v.scale};
   const nextPan={x:x-world.x*nextScale,y:y-world.y*nextScale};
   setZoom(nextZoom);setPan(nextPan);viewRef.current={...v,zoom:nextZoom,pan:nextPan,scale:nextScale,origin:{...nextPan}};
   clearTimeout(wheelTimer.current);wheelTimer.current=setTimeout(()=>{const latest=viewRef.current;if(latest.snap){const aligned=alignCamera(latest.size,latest.baseScale,latest.zoom,latest.pan);setZoom(aligned.zoom);setPan(aligned.pan)}},160);
  };
  canvas.addEventListener('wheel',wheel,{passive:false});return()=>{canvas.removeEventListener('wheel',wheel);clearTimeout(wheelTimer.current)};
 },[]);

 useEffect(()=>{if(!playing)return;let raf,last=performance.now(),p=position,t=sceneTime;const tick=now=>{const elapsed=(now-last)/1000;p+=elapsed/duration;t+=elapsed;last=now;const end=loop?frames.length:frames.length===1?Math.max(1,symbolCycleDuration(shapes,project.symbols)/duration):frames.length-1;if(p>=end){if(loop)p%=frames.length;else{setPlaying(false);setFrame(frames.length-1);setPosition(frames.length-1);setSceneTime(t);return}}setPosition(frames.length===1?0:p);setSceneTime(t);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing,duration,loop,frames.length]);
 useEffect(()=>{const key=e=>{if(e.target.closest('input,select,textarea,.camera-window,.mini-menu,.frame-card')||settings||exportOpen||voiceMode||recordedMovie)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&['c','v'].includes(e.key.toLowerCase())){e.preventDefault();e.key.toLowerCase()==='c'?copySelection():pasteSelection();return}if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteShape()}else if(e.key==='Escape'){clearSelection();setPlaying(false)}else if(e.key==='ArrowRight')chooseFrame(Math.min(frames.length-1,frame+1));else if(e.key==='ArrowLeft')chooseFrame(Math.max(0,frame-1));else if(e.key.toLowerCase()==='n')addFrame();else{const t=toolList.find(t=>t[3].toLowerCase()===e.key.toLowerCase());if(t){setPlaying(false);setTool(t[0])}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 useEffect(()=>{if(!settings)return;settingsRef.current?.querySelector('button')?.focus();const onKey=e=>{if(e.key==='Escape')setSettings(false);if(e.key==='Tab'){const els=[...settingsRef.current.querySelectorAll('button:not(:disabled),input,select')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('keydown',onKey);settingsButtonRef.current?.focus()}},[settings]);
 const toWorld=p=>{const r=canvasRef.current.getBoundingClientRect();return{x:(p.clientX-r.left-origin.x)/scale,y:(p.clientY-r.top-origin.y)/scale}};
 const snapped=p=>snap?{x:Math.round(p.x/spacing)*spacing,y:Math.round(p.y/spacing)*spacing}:p;
 function endpoint(p,id){const result=snapEndpoint(resolveShapes(framesRef.current,frame),p,id,scale,snap,spacing);setSnapHint(snap?result.point:null);return result}
 function showTouch(e,p){if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const r=canvasRef.current.getBoundingClientRect();setTouchPreview({x:e.clientX-r.left,y:e.clientY-r.top,world:p})}
 function hit(p,s){const q=worldToLocal(s,p),pad=14/scale;if(s.type==='circle')return((q.x-s.w/2)/(Math.abs(s.w/2)+pad))**2+((q.y-s.h/2)/(Math.abs(s.h/2)+pad))**2<=1;if((s.type==='rect'||s.type==='symbol'))return q.x>=-pad&&q.y>=-pad&&q.x<=s.w+pad&&q.y<=s.h+pad;for(let t=0;t<=1;t+=.015){const x=2*(1-t)*t*s.cx+t*t*s.w,y=2*(1-t)*t*s.cy+t*t*s.h;if(Math.hypot(q.x-x,q.y-y)<pad+s.stroke)return true}return false}
 function pointerDown(e){if(voiceMode||e.button>1)return;setManipulating(true);e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});if(pointers.current.size===2){const ps=[...pointers.current.values()],g=gesture.current;if(g?.beforeProject){setProject(g.beforeProject);setHistory(h=>h.slice(0,g.historyLength))}const center={clientX:(ps[0].clientX+ps[1].clientX)/2,clientY:(ps[0].clientY+ps[1].clientY)/2};gesture.current={type:'pinch',distance:Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),zoom,world:toWorld(center)};setSnapHint(null);setTouchPreview(null);setMarquee(null);if(g?.selected){setSelected(g.selected);setSelectedPoints(g.points)}return}if(playing||pointers.current.size>1)return;
 const p=toWorld(e),baseline={beforeProject:project,historyLength:history.length,selected:[...selected],points:structuredClone(selectedPoints)};if(e.button===1){gesture.current={type:'pan',start:{x:e.clientX,y:e.clientY},pan};return}
 if(tool==='select'){
  const node=[...shapes].reverse().filter(s=>s.type==='line').flatMap(s=>Object.entries(lineGeometry(s)).map(([key,point])=>({shape:s,key,point,distance:Math.hypot(p.x-point.x,p.y-point.y)*scale}))).filter(n=>n.distance<12).sort((a,b)=>a.distance-b.distance)[0];
  if(node){let ids=selected,points=selectedPoints;const already=points[node.shape.id]?.includes(node.key)&&!ids.includes(node.shape.id);if(!already){ids=e.shiftKey?ids:[];points=mergePoints(e.shiftKey?points:{},{[node.shape.id]:[node.key]})}else if(e.shiftKey){points={...points,[node.shape.id]:points[node.shape.id].filter(k=>k!==node.key)};if(!points[node.shape.id].length)delete points[node.shape.id];setSelectedPoints(points);return}setSelected(ids);setSelectedPoints(points);const single=!ids.length&&Object.values(points).flat().length===1;gesture.current={...baseline,type:'points',start:p,anchor:node.point,key:node.key,shape:node.shape,shapes,ids,points,single,moved:false};return}
  if(shape&&shape.type!=='line'&&!e.shiftKey&&!(shape.type==='symbol'&&lastTap.current?.id===shape.id&&performance.now()-lastTap.current.time<350)){const q=worldToLocal(shape,p),handles=[{x:0,y:0,key:'scale-tl'},{x:shape.w,y:0,key:'scale-tr'},{x:0,y:shape.h,key:'scale-bl'},{x:shape.w,y:shape.h,key:'scale-br'}],h=handles.find(h=>Math.hypot(q.x-h.x,q.y-h.y)<16/scale);if(h){gesture.current={...baseline,type:h.key,start:p,shape:{...shape},moved:false};return}}
  const target=[...shapes].reverse().find(s=>hit(p,s));
  if(target){const ids=e.shiftKey?(selected.includes(target.id)?selected.filter(id=>id!==target.id):[...selected,target.id]):selected.includes(target.id)?selected:[target.id],points=e.shiftKey||selected.includes(target.id)?selectedPoints:{};setSelected(ids);setSelectedPoints(points);if(ids.length===1&&target.type!=='symbol')setDrawingStyle(old=>({...old,color:target.color,strokeColor:target.strokeColor||target.color,stroke:target.stroke,...(target.type!=='line'?{fill:!!target.fill}:{})}));if(ids.includes(target.id))gesture.current={...baseline,type:'move',start:p,shape:{...target},shapes,ids,points,moved:false};return}
  const base=e.shiftKey?selected:[],basePoints=e.shiftKey?selectedPoints:{};setSelected(base);setSelectedPoints(basePoints);setMarquee({start:p,end:p});gesture.current={...baseline,type:'box',start:p,base,basePoints};return;
 }
 const id=uid(),connection=tool==='line'?endpoint(p,id):{point:snapped(p),link:null},start=connection.point,s={id,type:tool,name:tool==='rect'?'Square':tool==='circle'?'Circle':'Line',x:start.x,y:start.y,w:0,h:0,cx:0,cy:0,...newShapeStyle(tool,drawingStyle),opacity:1,rotation:0,visible:true,startLink:connection.link,endLink:null};if(tool==='line')showTouch(e,p);remember();patch(id,s,false);setSelected([id]);setSelectedPoints({});gesture.current={...baseline,type:'draw',start,shape:s};
 }
 function pointerMove(e){if(pointers.current.has(e.pointerId))pointers.current.set(e.pointerId,{clientX:e.clientX,clientY:e.clientY});const g=gesture.current;if(!g)return;if(g.type==='pinch'){const ps=[...pointers.current.values()];if(ps.length!==2)return;const distance=Math.hypot(ps[1].clientX-ps[0].clientX,ps[1].clientY-ps[0].clientY),nextZoom=Math.max(.4,Math.min(MAX_ZOOM,g.zoom*distance/Math.max(1,g.distance))),nextScale=baseScale*nextZoom,r=canvasRef.current.getBoundingClientRect(),center={x:(ps[0].clientX+ps[1].clientX)/2-r.left,y:(ps[0].clientY+ps[1].clientY)/2-r.top};const nextPan={x:center.x-g.world.x*nextScale,y:center.y-g.world.y*nextScale};g.camera={zoom:nextZoom,pan:nextPan};setZoom(nextZoom);setPan(nextPan);return}if(g.type==='pan'){setPan({x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y});return}
 const raw=toWorld(e),p=snapped(raw),s=g.shape,dx=raw.x-g.start.x,dy=raw.y-g.start.y;
 if(g.type==='box'){const parts=boxSelectParts(shapes,g.start,raw);setMarquee({start:g.start,end:raw});setSelected([...new Set([...g.base,...parts.ids])]);setSelectedPoints(mergePoints(g.basePoints,parts.points));return}
 if((g.type==='draw'&&s.type==='line')||(g.type==='points'&&g.single))showTouch(e,raw);
 if(g.type==='move'){if(!g.moved&&Math.hypot(dx,dy)*scale<4)return;if(!g.moved){remember();g.moved=true}const point=snapped({x:s.x+dx,y:s.y+dy});patchMany(moveParts(g.shapes,g.ids,g.points,point.x-s.x,point.y-s.y),false);return}
 if(g.type==='points'){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}if(g.single){const geometry=lineGeometry(s),point={x:g.anchor.x+dx,y:g.anchor.y+dy},target=g.key==='control'?{point:snapped(point)}:endpoint(point,s.id);geometry[g.key]=target.point;setSnapHint(snap?target.point:null);patch(s.id,{...fromLinePoints(geometry.start,geometry.end,geometry.control),...(g.key==='control'?{}:{[g.key+'Link']:target.link})},false)}else{const point=snapped({x:g.anchor.x+dx,y:g.anchor.y+dy});patchMany(moveParts(g.shapes,g.ids,g.points,point.x-g.anchor.x,point.y-g.anchor.y),false)}return}
 if(g.type==='draw'){if(s.type==='line'){const target=endpoint(raw,s.id),end=target.point;patch(s.id,{...fromLinePoints(g.start,end,{x:(g.start.x+end.x)/2,y:(g.start.y+end.y)/2}),endLink:target.link},false)}else{let w=p.x-g.start.x,h=p.y-g.start.y;if(e.shiftKey){const a=Math.max(Math.abs(w),Math.abs(h));w=Math.sign(w||1)*a;h=Math.sign(h||1)*a}patch(s.id,{x:Math.min(g.start.x,g.start.x+w),y:Math.min(g.start.y,g.start.y+h),w:Math.abs(w),h:Math.abs(h)},false)}}
 if(g.type.startsWith('scale-')){if(!g.moved&&Math.hypot(dx,dy)*scale<3)return;if(!g.moved){remember();g.moved=true}const q=worldToLocal(s,p),corner=g.type.slice(6);let left=0,top=0,right=s.w,bottom=s.h;if(corner[1]==='l')left=Math.min(q.x,s.w-20);else right=Math.max(20,q.x);if(corner[0]==='t')top=Math.min(q.y,s.h-20);else bottom=Math.max(20,q.y);if(e.shiftKey){const height=(right-left)*s.h/s.w;if(corner[0]==='t')top=bottom-height;else bottom=top+height}const w=right-left,h=bottom-top,center=localToWorld(s,{x:(left+right)/2,y:(top+bottom)/2});patch(s.id,{x:center.x-w/2,y:center.y-h/2,w,h},false)}
 }
 function pointerUp(e){pointers.current.delete(e.pointerId);setManipulating(false);setMarquee(null);const g=gesture.current;if(g?.type==='pinch'&&snap){const camera=g.camera||{zoom,pan};const aligned=alignCamera(size,baseScale,camera.zoom,camera.pan);setZoom(aligned.zoom);setPan(aligned.pan)}if(g?.type==='draw'){const s=resolveShapes(framesRef.current,frame).find(s=>s.id===g.shape.id);if(s&&Math.abs(s.w)+Math.abs(s.h)<4)patch(s.id,{w:160,h:s.type==='line'?0:160,cx:80,cy:s.type==='line'?0:80,endLink:null},false);setTool('select')}if(e.type!=='pointercancel'&&(g?.type==='move'||g?.type.startsWith('scale-'))&&!g.moved&&g.shape.type==='symbol'){const now=performance.now(),previous=lastTap.current;if(previous?.id===g.shape.id&&now-previous.time<350&&Math.hypot(e.clientX-previous.x,e.clientY-previous.y)<20)enterSymbol(g.shape);else lastTap.current={id:g.shape.id,time:now,x:e.clientX,y:e.clientY}}gesture.current=null;setSnapHint(null);setTouchPreview(null)}
 useEffect(()=>{const draw=()=>{const canvas=canvasRef.current,ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(size.w*dpr)||canvas.height!==Math.round(size.h*dpr)){canvas.width=Math.round(size.w*dpr);canvas.height=Math.round(size.h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size.w,size.h);
 if(grid)drawGrid(ctx,size.w,size.h,scale,origin,level);
 ctx.save();ctx.translate(origin.x,origin.y);ctx.scale(scale,scale);const rendered=voiceMode?voiceScene.current:playing?interpolateShapes(frames,position,easing,loop):shapes;rendered.forEach(s=>drawShape(ctx,s,{symbols:project.symbols,time:voiceMode?voiceTime.current:sceneTime}));
 if(!playing&&!voiceMode){
  for(const s of shapes.filter(s=>s.type==='line'&&tool==='select')){const geometry=lineGeometry(s),active=selected.includes(s.id)||selectedPoints[s.id]?.length;if(active){ctx.strokeStyle='#b6a1fb88';ctx.lineWidth=1/scale;ctx.setLineDash([4/scale,4/scale]);ctx.beginPath();ctx.moveTo(geometry.start.x,geometry.start.y);ctx.lineTo(geometry.control.x,geometry.control.y);ctx.lineTo(geometry.end.x,geometry.end.y);ctx.stroke();ctx.setLineDash([])}for(const[key,p]of Object.entries(geometry)){const picked=selected.includes(s.id)||selectedPoints[s.id]?.includes(key),linked=s[key+'Link'];ctx.beginPath();ctx.arc(p.x,p.y,(picked?5:3)/scale,0,Math.PI*2);ctx.fillStyle=picked?'#b6a1fb':'#25272d';ctx.strokeStyle=linked?'#b4d7a0':picked?'#c6b2ff':'#737080';ctx.lineWidth=1/scale;ctx.fill();ctx.stroke()}}
  for(const s of selectedShapes.filter(s=>s.type!=='line')){ctx.save();ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-s.w/2,-s.h/2);ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;ctx.strokeRect(0,0,s.w,s.h);if(shape)for(const[x,y]of[[0,0],[s.w,0],[0,s.h],[s.w,s.h]]){ctx.fillStyle='#202229';ctx.beginPath();ctx.arc(x,y,4/scale,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
 }
 if(bounds&&(selectedShapes.length>1||Object.values(selectedPoints).flat().length>1)&&!playing&&!voiceMode){ctx.strokeStyle='#b6a1fb';ctx.lineWidth=1/scale;ctx.setLineDash([5/scale,4/scale]);ctx.strokeRect(bounds.left-8/scale,bounds.top-8/scale,bounds.right-bounds.left+16/scale,bounds.bottom-bounds.top+16/scale);ctx.setLineDash([])}
 if(snapHint){ctx.strokeStyle='#b4d7a0';ctx.lineWidth=2/scale;ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,11/scale,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#b4d7a0';ctx.beginPath();ctx.arc(snapHint.x,snapHint.y,3/scale,0,Math.PI*2);ctx.fill()}ctx.restore();
 };renderScene.current=draw;draw();return()=>{renderScene.current=null}},[project,frames,frame,selected,selectedPoints,position,sceneTime,playing,size,zoom,pan,grid,easing,loop,snapHint,voiceMode,tool]);
 const menuWidth=Math.min(selectedShapes.some(s=>s.startLink||s.endLink)?484:440,size.w-16),menuX=bounds?Math.max(8,Math.min(size.w-menuWidth-8,origin.x+(bounds.left+bounds.right)*scale/2-menuWidth/2)):8;
 const above=bounds?origin.y+bounds.top*scale-62:8,menuY=Math.max(8,Math.min(size.h-60,above>=8?above:origin.y+(bounds?.bottom||0)*scale+16));
 return <main className="editor"><section className="stage" ref={stageRef}><canvas className={`main-canvas tool-${tool}`} ref={canvasRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} aria-label="Animation drawing canvas"/>{touchPreview&&<TouchPreview touch={touchPreview} size={size} scale={scale} shapes={shapes} selected={gesture.current?.shape?.id} grid={grid} hint={snapHint} level={level} symbols={project.symbols} time={sceneTime}/>}{marquee&&<div className="selection-box" style={{left:origin.x+Math.min(marquee.start.x,marquee.end.x)*scale,top:origin.y+Math.min(marquee.start.y,marquee.end.y)*scale,width:Math.abs(marquee.end.x-marquee.start.x)*scale,height:Math.abs(marquee.end.y-marquee.start.y)*scale}}/>}
 {selectedShapes.length>0&&!playing&&!voiceMode&&!manipulating&&!settings&&!exportOpen&&!recordedMovie&&<div className="mini-menu shape-menu" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();clearSelection()}}} role="toolbar" aria-label={selectedShapes.length===1?'Shape actions':`${selectedShapes.length} selected shapes`} style={{left:menuX,top:menuY,maxWidth:menuWidth}}>
 <label className="menu-color" title="Fill color"><span style={{background:selectedShapes[0].color}}/><input type="color" aria-label="Fill color" value={selectedShapes[0].color} onChange={e=>{setDrawingStyle(s=>({...s,color:e.target.value}));patchMany(styleSelection(selectedShapes,'color',e.target.value))}}/></label>
 <label className="menu-color stroke-color" title="Stroke color"><span style={{borderColor:selectedShapes[0].strokeColor||selectedShapes[0].color}}/><input type="color" aria-label="Stroke color" value={selectedShapes[0].strokeColor||selectedShapes[0].color} onChange={e=>{setDrawingStyle(s=>({...s,strokeColor:e.target.value}));patchMany(styleSelection(selectedShapes,'strokeColor',e.target.value))}}/></label>
 <label className="stroke-width" title="Stroke width"><span>Stroke</span><input aria-label="Stroke width" type="number" inputMode="decimal" min="0" max="80" step="1" value={selectedShapes[0].stroke} onChange={e=>{setDrawingStyle(s=>({...s,stroke:Math.max(0,Math.min(80,Number(e.target.value)||0))}));patchMany(styleSelection(selectedShapes,'stroke',e.target.value))}}/></label>
 <IconButton icon={PaintBucket} label="Toggle fill" disabled={selectedShapes.every(s=>s.type==='line')} active={selectedShapes.every(s=>s.type==='line'||s.fill)} onClick={toggleFill}/>
 <IconButton icon={Copy} label="Copy selected shapes" onClick={copySelection}/><IconButton icon={ClipboardPaste} label="Paste shapes" disabled={!clipboard} onClick={pasteSelection}/><IconButton icon={Group} label="Create symbol" onClick={makeSymbol}/>{shape?.type==='symbol'&&<IconButton icon={LogIn} label="Edit symbol" onClick={()=>enterSymbol(shape)}/>}<IconButton icon={Trash2} label="Delete selected shapes" onClick={deleteShape}/>{selectedShapes.some(s=>s.startLink||s.endLink)&&<IconButton icon={Unlink} label="Disconnect selected lines" onClick={unlink}/>}</div>}
 {scope&&!voiceMode&&<button className="symbol-exit" onClick={exitSymbol} aria-label="Exit symbol"><LogOut size={16}/><span>Exit symbol{path.length>1?` · ${path.length}`:''}</span></button>}
 <CameraOverlay camera={camera} size={size}/></section>
 <div className="controls">{voiceMode?<Voiceover getRecordingScene={getRecordingScene} camera={camera} canvasRef={canvasRef} fps={movieFps} orientation={size.orientation} onPaused={setVoicePaused} onDone={finishVoice} onExport={()=>setExportOpen(true)}/>:<div className="tool-row"><div className="undo-tools" aria-label="History and playback"><IconButton icon={Undo2} label="Undo (⌘Z)" disabled={!history.length} onClick={undo}/><IconButton icon={Redo2} label="Redo (⌘⇧Z)" disabled={!future.length} onClick={redo}/><IconButton icon={playing?Pause:Play} label={playing?'Pause (Space)':'Play (Space)'} className="play-button" disabled={!canPlay} onClick={togglePlay}/></div><nav className="tool-scroll" aria-label="Drawing tools and settings">{toolList.map(([id,Icon,label,key])=><span className="tool-pair" key={id}><IconButton icon={Icon} label={`${label} (${key})`} active={tool===id} onClick={()=>{setPlaying(false);setTool(id)}}/>{id==='select'&&<IconButton icon={Magnet} label="Snap to grid and shapes" active={snap} onClick={()=>setSnap(!snap)}/>}</span>)}<span className="separator"/><IconButton icon={Copy} label="Copy selected shapes (⌘C)" disabled={!selectedShapes.length} onClick={copySelection}/><IconButton icon={ClipboardPaste} label="Paste shapes (⌘V)" disabled={!clipboard} onClick={pasteSelection}/><IconButton icon={Focus} label="Reset camera" onClick={resetCamera}/>{scope&&<IconButton icon={LogOut} label="Exit symbol" onClick={exitSymbol}/>}<IconButton icon={Film} label="Recording area" onClick={enterVoice}/><button ref={settingsButtonRef} className="icon-button" aria-label="Settings" title="Settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></nav></div>}
 <FrameTimeline key={scope||'main'} symbols={project.symbols} duration={duration} frames={frames} frame={frame} playing={playing} position={position} recording={voiceMode} onChoose={voiceMode?voiceFrame:chooseFrame} onAdd={addFrame} onCopy={copyFrame} onDelete={removeFrame} onReorder={reorderFrame}/></div>
 {exportOpen&&<MovieExport getCameraOverlay={camera.getOverlay} frames={frames} symbols={project.symbols} duration={duration} loop={loop} easing={easing} fps={movieFps} onFpsChange={setMovieFps} view={{width:size.w,height:size.h,orientation:size.orientation,scale,origin,gridLevel:level}} onClose={()=>setExportOpen(false)}/>}
 {recordedMovie&&<MovieSave recording={recordedMovie} onClose={()=>setRecordedMovie(null)}/>}
 {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><div ref={settingsRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e=>e.stopPropagation()}><div className="modal-heading"><h2 id="settings-title">Settings</h2><IconButton icon={X} label="Close settings" onClick={()=>setSettings(false)}/></div><label className="settings-row"><span>Seconds between frames</span><input type="number" inputMode="decimal" min="0.1" max="30" step="0.1" value={duration} onChange={e=>setDuration(Math.max(.1,Math.min(30,+e.target.value||1)))}/></label><label className="settings-row"><span>Movie frame rate</span><select value={movieFps} onChange={e=>setMovieFps(Number(e.target.value))}>{MOVIE_FPS.map(fps=><option key={fps} value={fps}>{fps} fps</option>)}</select></label><label className="settings-row"><span>Transition</span><select value={easing} onChange={e=>setEasing(e.target.value)}><option value="smooth">Smooth</option><option value="linear">Linear</option></select></label><label className="settings-row"><span>Loop playback</span><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/></label><label className="settings-row"><span>Show grid</span><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/></label><label className="settings-row"><span>Snap to grid and shapes</span><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/></label><button className="done-button" onClick={()=>setSettings(false)}>Done</button></div></div>}
 </main>
}
