'use client';
import {useState,useEffect,useRef} from 'react';
import {Plus,Copy,Trash2} from 'lucide-react';
import {resolveShapes,drawShape} from '../lib/animation';
function Thumbnail({frames,index}){const ref=useRef(null);useEffect(()=>{const ctx=ref.current.getContext('2d');ctx.clearRect(0,0,180,180);ctx.save();ctx.translate(0,25);ctx.scale(.19,.19);resolveShapes(frames,index).forEach(s=>drawShape(ctx,s));ctx.restore()},[frames,index]);return <canvas ref={ref} width="180" height="180"/>}
export default function FrameTimeline({frames,frame,playing,position,disabled,onChoose,onAdd,onCopy,onDelete,onReorder}){
 const strip=useRef(null),press=useRef(null),timer=useRef(null);
 const[menu,setMenu]=useState(null),[drag,setDrag]=useState(null);
 function open(index,node){onChoose(index);const r=node.getBoundingClientRect();setMenu({id:frames[index].id,x:Math.max(8,Math.min(window.innerWidth-184,r.left+r.width/2-88)),y:r.top-58})}
 function destination(x){const cards=[...strip.current.querySelectorAll('[data-frame]')];let best=0,distance=Infinity;cards.forEach((card,i)=>{const r=card.getBoundingClientRect(),d=Math.abs(x-(r.left+r.width/2));if(d<distance){best=i;distance=d}});return best}
 function down(e,index){if(disabled||e.button!==0||press.current)return;e.currentTarget.setPointerCapture(e.pointerId);const p={id:e.pointerId,index,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,rect:e.currentTarget.getBoundingClientRect(),scroll:strip.current.scrollLeft,active:false,moved:false,node:e.currentTarget};press.current=p;
  timer.current=setTimeout(()=>{if(press.current!==p)return;p.active=true;p.to=index;setMenu(null);setDrag(dragState(p));onChoose(index)},450);
 }
 function dragState(p){return{from:p.index,to:p.to,left:p.rect.left+p.lastX-p.x,top:p.rect.top+p.lastY-p.y,width:p.rect.width}}
 function move(e){const p=press.current;if(!p||p.id!==e.pointerId)return;p.lastX=e.clientX;p.lastY=e.clientY;if(p.active){e.preventDefault();p.to=destination(e.clientX);setDrag(dragState(p));return}if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>8){p.moved=true;clearTimeout(timer.current);setMenu(null);strip.current.scrollLeft=p.scroll-(e.clientX-p.x)}}
 function up(e,cancel=false){const p=press.current;if(!p||p.id!==e.pointerId)return;clearTimeout(timer.current);press.current=null;setDrag(null);if(cancel)return;if(p.active){if(p.index!==p.to)onReorder(p.index,p.to)}else if(!p.moved)open(p.index,p.node)}
 useEffect(()=>{if(!drag)return;let raf;function tick(){const p=press.current;if(!p?.active)return;const r=strip.current.getBoundingClientRect(),edge=44,speed=p.lastX<r.left+edge?-Math.min(12,(r.left+edge-p.lastX)/3):p.lastX>r.right-edge?Math.min(12,(p.lastX-r.right+edge)/3):0;if(speed){strip.current.scrollLeft+=speed;p.to=destination(p.lastX);setDrag(dragState(p))}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[!!drag]);
 useEffect(()=>{if(press.current?.active)return;strip.current?.querySelector(`[data-frame="${frame}"]`)?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'})},[frame,frames.length]);
 useEffect(()=>{if(disabled||playing)setMenu(null)},[disabled,playing]);
 useEffect(()=>{const close=e=>{if(!e.target.closest('.frame-menu,.frame-card'))setMenu(null)},key=e=>{if(e.key==='Escape')setMenu(null)};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);clearTimeout(timer.current)}},[]);
 const menuIndex=menu?frames.findIndex(f=>f.id===menu.id):-1;
 return <><nav className={`frame-strip ${drag?'reordering':''}`} aria-label="Animation frames" ref={strip} onScroll={()=>setMenu(null)}>{frames.map((f,i)=><button key={f.id} data-frame={i} aria-label={`Frame ${i+1}. Hold to reorder.`} aria-current={(playing?Math.floor(position):frame)===i?'true':undefined} aria-pressed={drag?.from===i} disabled={disabled} onPointerDown={e=>down(e,i)} onPointerMove={move} onPointerUp={e=>up(e)} onPointerCancel={e=>up(e,true)} onLostPointerCapture={e=>up(e,true)} onClick={e=>{if(e.detail===0)open(i,e.currentTarget)}} onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.stopPropagation();onReorder(i,Math.max(0,Math.min(frames.length-1,i+(e.key==='ArrowLeft'?-1:1))));setMenu(null)}}} className={`frame-card ${(playing?Math.floor(position):frame)===i?'current':''} ${drag?.from===i?'dragging':''} ${drag?.to===i&&drag.from!==i?(drag.to<drag.from?'drop-before':'drop-after'):''}`}><Thumbnail frames={frames} index={i}/><span className="frame-number">{String(i+1).padStart(2,'0')}</span><span className={`frame-key ${Object.keys(f.changes).length?'filled':''}`}/>{playing&&Math.floor(position)===i&&<span className="frame-progress" style={{width:`${(position%1)*100}%`}}/>}</button>)}{!disabled&&<button className="add-frame" onClick={()=>{setMenu(null);onAdd()}} aria-label="Add frame (N)" title="Add frame (N)"><Plus size={23} strokeWidth={1.5}/></button>}</nav>
 {drag&&<div className="frame-drag-preview" aria-hidden="true" style={{left:drag.left,top:drag.top,width:drag.width,height:drag.width}}><Thumbnail frames={frames} index={drag.from}/><span className="frame-number">{String(drag.from+1).padStart(2,'0')}</span></div>}
 {menuIndex>=0&&!disabled&&!playing&&<div className="mini-menu frame-menu" role="toolbar" aria-label={`Frame ${menuIndex+1} actions`} style={{left:menu.x,top:Math.max(8,menu.y)}}><button onClick={()=>{onCopy(menuIndex);setMenu(null)}}><Copy size={17}/><span>Copy</span></button><button disabled={frames.length<2} onClick={()=>{onDelete(menuIndex);setMenu(null)}}><Trash2 size={17}/><span>Delete</span></button></div>}
 </>
}
