'use client';
import {useState,useEffect,useRef} from 'react';
import useImages from './use-images';
import useElasticScroll from './use-elastic-scroll';
import {frameScrollTarget} from '../lib/elastic-scroll';
import {Plus,Copy,Trash2,Camera} from 'lucide-react';
import {FRAME_TIMES,frameMultiplier,frameStart} from '../lib/timing';
import {resolveShapes,drawShape} from '../lib/animation';
import {hasCameraFrames,resolveCamera} from '../lib/timeline-camera';
function Thumbnail({frames,index,symbols,duration,mainTimeline}){const ref=useRef(null),imageVersion=useImages();useEffect(()=>{const ctx=ref.current.getContext('2d');ctx.clearRect(0,0,180,180);ctx.save();ctx.translate(0,25);ctx.scale(.19,.19);if(mainTimeline&&hasCameraFrames(frames)){const camera=resolveCamera(frames,index);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y)}resolveShapes(frames,index).forEach(s=>drawShape(ctx,s,{symbols,time:frameStart(frames,index,duration)}));ctx.restore()},[frames,index,symbols,duration,mainTimeline,imageVersion]);return <canvas ref={ref} width="180" height="180"/>}
export default function FrameTimeline({frames,symbols,duration,frame,playing,position,disabled=false,recording=false,onChoose,onAdd,onCopy,onDelete,onReorder,onTiming,mainTimeline=false,onCamera}){
 const strip=useRef(null),press=useRef(null),timer=useRef(null),previousCount=useRef(frames.length);
 const scrolling=useElasticScroll(strip);
 const[menu,setMenu]=useState(null),[drag,setDrag]=useState(null);
 function open(index,node){const showMenu=!recording&&!playing&&index===frame;onChoose(index);if(!showMenu||menu?.id===frames[index].id){setMenu(null);return}const r=node.getBoundingClientRect();setMenu({id:frames[index].id,x:Math.max(8,Math.min(window.innerWidth-184,r.left+r.width/2-88)),y:r.top-(mainTimeline?158:116)})}
 function destination(x){const cards=[...strip.current.querySelectorAll('[data-frame]')];let best=0,distance=Infinity;cards.forEach((card,i)=>{const r=card.getBoundingClientRect(),d=Math.abs(x-(r.left+r.width/2));if(d<distance){best=i;distance=d}});return best}
 function down(e,index){if(disabled||e.button!==0||press.current)return;scrolling.begin(e.clientX,e.timeStamp);e.currentTarget.setPointerCapture(e.pointerId);const p={id:e.pointerId,index,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,rect:e.currentTarget.getBoundingClientRect(),scroll:strip.current.scrollLeft,active:false,moved:false,node:e.currentTarget};press.current=p;
  if(!recording&&index!=null)timer.current=setTimeout(()=>{if(press.current!==p)return;scrolling.settle();p.rect=p.node.getBoundingClientRect();p.active=true;p.to=index;setMenu(null);setDrag(dragState(p));onChoose(index)},450);
 }
 function dragState(p){return{from:p.index,to:p.to,left:p.rect.left+p.lastX-p.x,top:p.rect.top+p.lastY-p.y,width:p.rect.width}}
 function move(e){const p=press.current;if(!p||p.id!==e.pointerId)return;p.lastX=e.clientX;p.lastY=e.clientY;if(p.active){e.preventDefault();p.to=destination(e.clientX);setDrag(dragState(p));return}if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>8){p.moved=true;clearTimeout(timer.current);setMenu(null);scrolling.move(e.clientX,e.timeStamp)}}
 function up(e,cancel=false){const p=press.current;if(!p||p.id!==e.pointerId)return;clearTimeout(timer.current);press.current=null;setDrag(null);if(p.active){scrolling.settle();if(!cancel&&p.index!==p.to)onReorder(p.index,p.to)}else{scrolling.release(e.timeStamp,cancel);if(!cancel&&!p.moved&&p.index!=null)open(p.index,p.node)}}
 useEffect(()=>{if(!drag)return;let raf;function tick(){const p=press.current;if(!p?.active)return;const r=strip.current.getBoundingClientRect(),edge=44,speed=p.lastX<r.left+edge?-Math.min(12,(r.left+edge-p.lastX)/3):p.lastX>r.right-edge?Math.min(12,(p.lastX-r.right+edge)/3):0;if(speed){strip.current.scrollLeft+=speed;p.to=destination(p.lastX);setDrag(dragState(p))}raf=requestAnimationFrame(tick)}raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[!!drag]);
 useEffect(()=>{const previous=previousCount.current;previousCount.current=frames.length;if(press.current?.active)return;const row=strip.current,card=row?.querySelector(`[data-frame="${frame}"]`);if(!row)return;const target=frameScrollTarget({previousCount:previous,count:frames.length,canAdd:!disabled&&!recording,current:row.scrollLeft,max:scrolling.max(),viewport:row.getBoundingClientRect(),card:card?.getBoundingClientRect()});if(Math.abs(target-row.scrollLeft)>.5)scrolling.scrollTo(target)},[frame,frames.length]);
 useEffect(()=>{if(disabled||playing||recording)setMenu(null)},[disabled,playing,recording]);
 useEffect(()=>{const close=e=>{if(!e.target.closest('.frame-menu,.frame-card'))setMenu(null)},key=e=>{if(e.key==='Escape')setMenu(null)};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);clearTimeout(timer.current)}},[]);
 const menuIndex=menu?frames.findIndex(f=>f.id===menu.id):-1;
 return <><div className="frame-scroll-viewport"><nav className={`frame-strip ${drag?'reordering':''}`} aria-label="Animation frames" ref={strip} onScroll={()=>setMenu(null)} onWheel={()=>setMenu(null)} onPointerDown={e=>{if(!e.target.closest('button'))down(e,null)}} onPointerMove={e=>{if(press.current?.index==null)move(e)}} onPointerUp={e=>{if(press.current?.index==null)up(e)}} onPointerCancel={e=>{if(press.current?.index==null)up(e,true)}} onLostPointerCapture={e=>{if(press.current?.index==null)up(e,true)}}>{frames.map((f,i)=><button key={f.id} data-frame={i} aria-label={recording?`Transition to frame ${i+1}`:`Frame ${i+1}. Hold to reorder.`} aria-current={(playing?Math.floor(position):frame)===i?'true':undefined} aria-pressed={drag?.from===i} disabled={disabled} onPointerDown={e=>down(e,i)} onPointerMove={move} onPointerUp={e=>up(e)} onPointerCancel={e=>up(e,true)} onLostPointerCapture={e=>up(e,true)} onClick={e=>{if(e.detail===0)open(i,e.currentTarget)}} onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{if(!recording&&e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.stopPropagation();onReorder(i,Math.max(0,Math.min(frames.length-1,i+(e.key==='ArrowLeft'?-1:1))));setMenu(null)}}} className={`frame-card ${(playing?Math.floor(position):frame)===i?'current':''} ${drag?.from===i?'dragging':''} ${drag?.to===i&&drag.from!==i?(drag.to<drag.from?'drop-before':'drop-after'):''}`}><Thumbnail mainTimeline={mainTimeline} symbols={symbols} duration={duration} frames={frames} index={i}/><span className="frame-number">{String(i+1).padStart(2,'0')}</span><span className="frame-time">{frameMultiplier(f)!==1?FRAME_TIMES.find(([value])=>value===frameMultiplier(f))[1]:''}</span><span className={`frame-key ${Object.keys(f.changes).length||(mainTimeline&&Object.keys(f.camera||{}).length)?'filled':''}`}/>{playing&&Math.floor(position)===i&&<span className="frame-progress" style={{width:`${(position%1)*100}%`}}/>}</button>)}{!disabled&&!recording&&<button className="add-frame" onClick={()=>{setMenu(null);onAdd()}} aria-label="Add frame (N)" title="Add frame (N)"><Plus size={23} strokeWidth={1.5}/></button>}</nav></div>
 {drag&&<div className="frame-drag-preview" aria-hidden="true" style={{left:drag.left,top:drag.top,width:drag.width,height:drag.width}}><Thumbnail mainTimeline={mainTimeline} symbols={symbols} duration={duration} frames={frames} index={drag.from}/><span className="frame-number">{String(drag.from+1).padStart(2,'0')}</span></div>}
 {menuIndex>=0&&!disabled&&!playing&&!recording&&<div className="mini-menu frame-menu" role="toolbar" aria-label={`Frame ${menuIndex+1} actions`} style={{left:menu.x,top:Math.max(8,menu.y)}}><label className="frame-timing"><span>Time</span><select aria-label="Frame duration multiplier" disabled={frames.length>1&&menuIndex===frames.length-1} title={menuIndex===frames.length-1?'The final frame loops immediately':undefined} value={frameMultiplier(frames[menuIndex])} onChange={e=>onTiming(menuIndex,Number(e.target.value))}>{FRAME_TIMES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{mainTimeline&&<button className="frame-camera" onClick={()=>{setMenu(null);onCamera?.()}}><Camera size={17}/><span>Camera</span></button>}<button onClick={()=>{onCopy(menuIndex);setMenu(null)}}><Copy size={17}/><span>Copy</span></button><button disabled={frames.length<2} onClick={()=>{onDelete(menuIndex);setMenu(null)}}><Trash2 size={17}/><span>Delete</span></button></div>}
 </>
}
