export const palette=['#b6a1fb','#e7e3d8','#b4d7a0','#e7aa8d','#8dbedc','#e19ab5'];
export const GRID_SIZE=80;
export function localToWorld(s,p){const a=s.rotation*Math.PI/180,x=p.x-s.w/2,y=p.y-s.h/2;return{x:s.x+s.w/2+x*Math.cos(a)-y*Math.sin(a),y:s.y+s.h/2+x*Math.sin(a)+y*Math.cos(a)}}
export function worldToLocal(s,p){const a=-s.rotation*Math.PI/180,x=p.x-s.x-s.w/2,y=p.y-s.y-s.h/2;return{x:x*Math.cos(a)-y*Math.sin(a)+s.w/2,y:x*Math.sin(a)+y*Math.cos(a)+s.h/2}}
export function linePoint(s,t){return localToWorld(s,{x:2*(1-t)*t*s.cx+t*t*s.w,y:2*(1-t)*t*s.cy+t*t*s.h})}
export function lineGeometry(s){return{start:linePoint(s,0),end:linePoint(s,1),control:localToWorld(s,{x:s.cx,y:s.cy})}}
export function fromLinePoints(start,end,control){return{x:start.x,y:start.y,w:end.x-start.x,h:end.y-start.y,cx:control.x-start.x,cy:control.y-start.y,rotation:0}}
export function anchorPoint(s,link){if(link.kind==='circle'&&s.type==='circle')return localToWorld(s,{x:s.w/2+Math.cos(link.angle)*s.w/2,y:s.h/2+Math.sin(link.angle)*s.h/2});if(link.kind==='line'&&s.type==='line')return linePoint(s,link.t);return null}
export function dependsOn(shapes,id,target,seen=new Set()){if(id===target)return true;if(seen.has(id))return false;seen.add(id);const s=shapes.find(s=>s.id===id);return [s?.startLink,s?.endLink].some(link=>link&&dependsOn(shapes,link.id,target,seen))}
export function resolveConnections(shapes){const byId=new Map(shapes.map(s=>[s.id,s])),resolved=new Map(),visiting=new Set();function resolve(id){if(resolved.has(id))return resolved.get(id);const s=byId.get(id);if(!s||visiting.has(id))return s;visiting.add(id);let result=s;if(s.type==='line'&&(s.startLink||s.endLink)){const base=lineGeometry(s);const find=link=>{if(!link||link.id===id||visiting.has(link.id))return null;const target=resolve(link.id);return target?anchorPoint(target,link):null};const start=find(s.startLink)||base.start,end=find(s.endLink)||base.end;const control={x:base.control.x+(start.x-base.start.x+end.x-base.end.x)/2,y:base.control.y+(start.y-base.start.y+end.y-base.end.y)/2};result={...s,...fromLinePoints(start,end,control)}}visiting.delete(id);resolved.set(id,result);return result}return shapes.map(s=>resolve(s.id))}
export function resolveShapes(frames,index){const shapes={};for(let i=0;i<=Math.min(index,frames.length-1);i++)for(const[id,patch]of Object.entries(frames[i].changes))shapes[id]={...shapes[id],...patch,id};return resolveConnections(Object.values(shapes).filter(s=>s.visible!==false&&s.type))}
export function findSnap(shapes,p,excludeId,radius){let best=null;let distance=radius;for(const s of shapes){if(s.id===excludeId||dependsOn(shapes,s.id,excludeId)||!['circle','line'].includes(s.type))continue;const count=s.type==='circle'?128:100;let bestT=0,d=Infinity;const pointAt=t=>s.type==='circle'?anchorPoint(s,{kind:'circle',angle:t*Math.PI*2}):linePoint(s,t);for(let i=0;i<=count;i++){const t=i/count,q=pointAt(t),next=Math.hypot(q.x-p.x,q.y-p.y);if(next<d){d=next;bestT=t}}let lo=bestT-1/count,hi=bestT+1/count;if(s.type==='line'){lo=Math.max(0,lo);hi=Math.min(1,hi)}for(let i=0;i<16;i++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3,pa=pointAt(a),pb=pointAt(b);if(Math.hypot(pa.x-p.x,pa.y-p.y)<Math.hypot(pb.x-p.x,pb.y-p.y))hi=b;else lo=a}let t=(lo+hi)/2;if(s.type==='line'){if(t<.025)t=0;else if(t>.975)t=1}const point=pointAt(t),next=Math.hypot(point.x-p.x,point.y-p.y);if(next<distance){distance=next;best={point,link:s.type==='circle'?{id:s.id,kind:'circle',angle:t*Math.PI*2}:{id:s.id,kind:'line',t}}}}return best}
function mixColor(a,b,t){const rgb=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));const x=rgb(a),y=rgb(b);return '#'+x.map((v,i)=>Math.round(v+(y[i]-v)*t).toString(16).padStart(2,'0')).join('')}
export function interpolateShapes(frames,position,easing='smooth'){const i=Math.floor(position),f=position-i,t=easing==='linear'?f:f*f*(3-2*f);const a=resolveShapes(frames,i),b=resolveShapes(frames,Math.min(i+1,frames.length-1));const interpolated=[...new Set([...a,...b].map(s=>s.id))].map(id=>{const start=a.find(s=>s.id===id),end=b.find(s=>s.id===id);if(!start)return{...end,opacity:end.opacity*t};if(!end)return{...start,opacity:start.opacity*(1-t)};const result={...start};for(const key of ['x','y','w','h','cx','cy','rotation','opacity','stroke'])result[key]=start[key]+(end[key]-start[key])*t;result.color=mixColor(start.color,end.color,t);for(const key of ['startLink','endLink'])if(JSON.stringify(start[key])!==JSON.stringify(end[key]))result[key]=null;return result});return resolveConnections(interpolated)}
export function drawShape(ctx,s){ctx.save();ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-s.w/2,-s.h/2);ctx.globalAlpha=s.opacity;ctx.fillStyle=s.color;ctx.strokeStyle=s.color;ctx.lineWidth=s.stroke;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(s.type==='circle')ctx.ellipse(s.w/2,s.h/2,Math.abs(s.w/2),Math.abs(s.h/2),0,0,Math.PI*2);else if(s.type==='rect')ctx.rect(0,0,s.w,s.h);else{ctx.moveTo(0,0);ctx.quadraticCurveTo(s.cx,s.cy,s.w,s.h)}if(s.type!=='line'&&s.fill)ctx.fill();else ctx.stroke();ctx.restore()}
export const initialFrames=[{id:'f1',changes:{circle:{type:'circle',name:'Circle',x:220,y:160,w:160,h:160,cx:80,cy:80,color:palette[0],fill:true,stroke:3,opacity:1,rotation:0,visible:true},square:{type:'rect',name:'Square',x:500,y:240,w:140,h:140,cx:70,cy:70,color:palette[1],fill:false,stroke:3,opacity:1,rotation:0,visible:true},line:{type:'line',name:'Line',x:260,y:420,w:260,h:-60,cx:120,cy:40,color:palette[2],fill:false,stroke:4,opacity:1,rotation:0,visible:true}}},{id:'f2',changes:{circle:{x:400,y:220,w:200,h:200},square:{x:220,y:160,rotation:45},line:{cy:-160}}},{id:'f3',changes:{circle:{x:580,y:140,w:120,h:120,color:palette[3]},square:{x:350,y:300,rotation:90},line:{w:380,cy:90}}}];
