import {imageBitmap} from './images.js';
import {brushPoint} from './brush.js';
import {freeformPoint,freeformSegments,canFill,DEFAULT_SMOOTHNESS} from './freeform.js';
import {timelinePosition,timelineSeconds} from './timing.js';
import {IDENTITY,shapeMatrix,transformPoint,inverse,tintColor} from './matrix.js';
import {strokeDash} from './defaults.js';
export const GRID_SIZE=80;
export function localToWorld(s,p){return transformPoint(shapeMatrix(s),p)}
export function worldToLocal(s,p){return transformPoint(inverse(shapeMatrix(s)),p)}
export function linePoint(s,t){return localToWorld(s,s.lineKind==='freeform'?freeformPoint(s,t):s.lineKind==='brush'?brushPoint(s.path,t):s.lineKind==='straight'?{x:t*s.w,y:t*s.h}:{x:2*(1-t)*t*s.cx+t*t*s.w,y:2*(1-t)*t*s.cy+t*t*s.h})}
export function lineGeometry(s){if(['brush','freeform'].includes(s.lineKind))return{start:localToWorld(s,s.path[0]),end:localToWorld(s,s.path.at(-1)),control:localToWorld(s,s.path[1])};return{start:linePoint(s,0),end:linePoint(s,1),control:localToWorld(s,s.lineKind==='straight'?{x:s.w/2,y:s.h/2}:{x:s.cx,y:s.cy})}}
export function lineHandles(s){if(['brush','freeform'].includes(s.lineKind))return Object.fromEntries(s.path.map((p,i)=>['p'+i,localToWorld(s,p)]));const points=lineGeometry(s);return s.lineKind==='straight'?{start:points.start,end:points.end}:points}
export function orderShapes(shapes){return shapes.map((shape,index)=>({shape,index})).sort((a,b)=>(a.shape.z??a.index)-(b.shape.z??b.index)||a.index-b.index).map(item=>item.shape)}
export function fromLinePoints(start,end,control){return{x:start.x,y:start.y,w:end.x-start.x,h:end.y-start.y,cx:control.x-start.x,cy:control.y-start.y,rotation:0,matrix:null}}
export function linePatch(s,start,end,control){if(['brush','freeform'].includes(s.lineKind))return{x:s.x,y:s.y,w:s.w,h:s.h,cx:s.cx,cy:s.cy,rotation:s.rotation,matrix:s.matrix||null,path:s.path};const m=inverse(s.matrix);return{...fromLinePoints(transformPoint(m,start),transformPoint(m,end),transformPoint(m,control)),matrix:s.matrix||null}}
export function patchLineHandles(s,handles){return ['brush','freeform'].includes(s.lineKind)?{path:s.path.map((p,i)=>handles['p'+i]?worldToLocal(s,handles['p'+i]):p)}:linePatch(s,handles.start,handles.end,handles.control||lineGeometry(s).control)}
export function anchorPoint(s,link){if(link.kind==='circle'&&s.type==='circle')return localToWorld(s,{x:s.w/2+Math.cos(link.angle)*s.w/2,y:s.h/2+Math.sin(link.angle)*s.h/2});if(link.kind==='line'&&s.type==='line')return linePoint(s,link.t);return null}
export function dependsOn(shapes,id,target,seen=new Set()){if(id===target)return true;if(seen.has(id))return false;seen.add(id);const s=shapes.find(s=>s.id===id);return [s?.startLink,s?.endLink].some(link=>link&&dependsOn(shapes,link.id,target,seen))}
export function resolveConnections(shapes){const byId=new Map(shapes.map(s=>[s.id,s])),resolved=new Map(),visiting=new Set();function resolve(id){if(resolved.has(id))return resolved.get(id);const s=byId.get(id);if(!s||visiting.has(id))return s;visiting.add(id);let result=s;if(s.type==='line'&&(s.startLink||s.endLink)){const base=lineGeometry(s);const find=link=>{if(!link||link.id===id||visiting.has(link.id))return null;const target=resolve(link.id);return target?anchorPoint(target,link):null};const start=find(s.startLink)||base.start,end=find(s.endLink)||base.end;const control={x:base.control.x+(start.x-base.start.x+end.x-base.end.x)/2,y:base.control.y+(start.y-base.start.y+end.y-base.end.y)/2};result={...s,...linePatch(s,start,end,control)}}visiting.delete(id);resolved.set(id,result);return result}return shapes.map(s=>resolve(s.id))}
export function resolveShapes(frames,index){const shapes={};for(let i=0;i<=Math.min(index,frames.length-1);i++)for(const[id,patch]of Object.entries(frames[i].changes))shapes[id]={...shapes[id],...patch,id};return orderShapes(resolveConnections(Object.values(shapes).filter(s=>s.visible!==false&&s.type)))}
export function findSnap(shapes,p,excludeId,radius){let best=null;let distance=radius;for(const s of shapes){if(s.id===excludeId||dependsOn(shapes,s.id,excludeId)||!['circle','line'].includes(s.type))continue;const count=s.type==='circle'?128:100;let bestT=0,d=Infinity;const pointAt=t=>s.type==='circle'?anchorPoint(s,{kind:'circle',angle:t*Math.PI*2}):linePoint(s,t);for(let i=0;i<=count;i++){const t=i/count,q=pointAt(t),next=Math.hypot(q.x-p.x,q.y-p.y);if(next<d){d=next;bestT=t}}let lo=bestT-1/count,hi=bestT+1/count;if(s.type==='line'){lo=Math.max(0,lo);hi=Math.min(1,hi)}for(let i=0;i<16;i++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3,pa=pointAt(a),pb=pointAt(b);if(Math.hypot(pa.x-p.x,pa.y-p.y)<Math.hypot(pb.x-p.x,pb.y-p.y))hi=b;else lo=a}let t=(lo+hi)/2;if(s.type==='line'){if(t<.025)t=0;else if(t>.975)t=1}const point=pointAt(t),next=Math.hypot(point.x-p.x,point.y-p.y);if(next<distance){distance=next;best={point,link:s.type==='circle'?{id:s.id,kind:'circle',angle:t*Math.PI*2}:{id:s.id,kind:'line',t}}}}return best}
function mixColor(a,b,t){const rgb=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));const x=rgb(a),y=rgb(b);return '#'+x.map((v,i)=>Math.round(v+(y[i]-v)*t).toString(16).padStart(2,'0')).join('')}
export function interpolateShapes(frames,position,easing='smooth',loop=false){const count=frames.length;if(!count)return [];const cycle=Math.max(1,count-1),p=loop?((position%cycle)+cycle)%cycle:Math.max(0,Math.min(position,count-1));const i=Math.floor(p),f=p-i,t=easing==='linear'?f:f*f*(3-2*f);const a=resolveShapes(frames,i),b=resolveShapes(frames,Math.min(i+1,count-1));return interpolateScene(a,b,t,'linear')}
export function interpolateScene(a,b,progress,easing='smooth'){const f=Math.max(0,Math.min(1,progress)),t=easing==='linear'?f:f*f*(3-2*f);if(t===0)return a;if(t===1)return b;const interpolated=[...new Set([...a,...b].map(s=>s.id))].map(id=>{const start=a.find(s=>s.id===id),end=b.find(s=>s.id===id);if(!start)return{...end,opacity:end.opacity*t};if(!end)return{...start,opacity:start.opacity*(1-t)};const result={...start};for(const key of ['x','y','w','h','cx','cy','rotation','opacity','stroke'])result[key]=start[key]+(end[key]-start[key])*t;if(start.lineKind==='freeform'&&end.lineKind==='freeform')result.smoothness=(start.smoothness??DEFAULT_SMOOTHNESS)+((end.smoothness??DEFAULT_SMOOTHNESS)-(start.smoothness??DEFAULT_SMOOTHNESS))*t;if(start.path&&end.path&&start.path.length===end.path.length)result.path=start.path.map((p,i)=>({x:p.x+(end.path[i].x-p.x)*t,y:p.y+(end.path[i].y-p.y)*t}));result.color=mixColor(start.color,end.color,t);if(start.tint||end.tint)result.tint=mixColor(start.tint||'#ffffff',end.tint||'#ffffff',t);if(start.matrix||end.matrix)result.matrix=(start.matrix||IDENTITY).map((v,i)=>v+((end.matrix||IDENTITY)[i]-v)*t);if(start.strokeColor||end.strokeColor)result.strokeColor=mixColor(start.strokeColor||start.color,end.strokeColor||end.color,t);for(const key of ['startLink','endLink'])if(JSON.stringify(start[key])!==JSON.stringify(end[key]))result[key]=null;return result});return orderShapes(resolveConnections(interpolated))}
export function drawShape(ctx,s,scene={},ancestors=[]){ctx.save();if(s.matrix)ctx.transform(...s.matrix);ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(s.rotation*Math.PI/180);ctx.translate(-s.w/2,-s.h/2);ctx.globalAlpha=(typeof ctx.globalAlpha==='number'?ctx.globalAlpha:1)*s.opacity;if(s.type==='symbol'){const definition=scene.symbols?.[s.symbolId];if(definition&&!ancestors.includes(s.symbolId)){const time=Math.max(0,(scene.time||0)+(s.timeOffset||0));ctx.scale(s.w/definition.width,s.h/definition.height);for(const child of interpolateShapes(definition.frames,timelinePosition(definition.frames,time,definition.duration||1),definition.easing||'linear',true))drawShape(ctx,child,{...scene,time,tint:tintColor(scene.tint||'#ffffff',s.tint||'#ffffff')},[...ancestors,s.symbolId])}ctx.restore();return}if(s.type==='image'){const image=imageBitmap(s.src,scene.tint||'#ffffff');if(image)ctx.drawImage(image,0,0,s.w,s.h);ctx.restore();return}ctx.fillStyle=tintColor(s.color,scene.tint);ctx.strokeStyle=tintColor(s.strokeColor||s.color,scene.tint);ctx.lineWidth=s.stroke;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash(strokeDash(s.strokeStyle,s.stroke));ctx.beginPath();if(s.type==='circle')ctx.ellipse(s.w/2,s.h/2,Math.abs(s.w/2),Math.abs(s.h/2),0,0,Math.PI*2);else if(s.type==='rect')ctx.rect(0,0,s.w,s.h);else if(s.lineKind==='freeform'){ctx.moveTo(s.path[0].x,s.path[0].y);for(const[,a,b,end]of freeformSegments(s))ctx.bezierCurveTo(a.x,a.y,b.x,b.y,end.x,end.y);if(s.closed)ctx.closePath()}else if(s.lineKind==='brush'){ctx.moveTo(s.path[0].x,s.path[0].y);for(let i=1;i+1<s.path.length;i+=2)ctx.quadraticCurveTo(s.path[i].x,s.path[i].y,s.path[i+1].x,s.path[i+1].y)}else{ctx.moveTo(0,0);if(s.lineKind==='straight')ctx.lineTo(s.w,s.h);else ctx.quadraticCurveTo(s.cx,s.cy,s.w,s.h)}if(canFill(s)&&s.fill)ctx.fill();if(s.strokeVisible!==false&&s.stroke>0)ctx.stroke();ctx.restore()}
export const initialFrames=[{id:'f1',changes:{}}];

export function symbolCycleDuration(shapes,symbols={},ancestors=[]){let longest=0;for(const shape of shapes){if(shape.type!=='symbol'||ancestors.includes(shape.symbolId))continue;const definition=symbols[shape.symbolId];if(!definition)continue;const children=definition.frames.flatMap((_,i)=>resolveShapes(definition.frames,i));longest=Math.max(longest,definition.frames.length>1?timelineSeconds(definition.frames,definition.duration||1):0,symbolCycleDuration(children,symbols,[...ancestors,shape.symbolId]))}return longest}
